# load data, DEGS, and cluster spatial

In [1]:
import os
import os, sys
import scipy
import pandas as pd
pd.set_option('display.max_rows', None)
import scanpy as sc
# import dask
import squidpy as sq
import numpy as np
import pickle

sc.settings.set_figure_params(dpi=300, facecolor="white", frameon=False, figsize=(4, 4))

RUNID=4
BASE_DIR = f'/nfs/team361/aa36/OnGit/inflow-reproducibility/Analysis/18_Melanoma_Jan20Runs/NonGit/RunOutputs/Jan26_20_00/Output_Path_Run{RUNID}/'
os.listdir(BASE_DIR)
adata=sc.read_h5ad(BASE_DIR +  'adata_inflowOutput_norm.h5ad' )
adata

/nfs/team361/aa36/PythonEnvs_2/envinflowdec27/lib/python3.11/site-packages/dask/dataframe/__init__.py:31: FutureWarning: The legacy Dask DataFrame implementation is deprecated and will be removed in a future version. Set the configuration option `dataframe.query-planning` to `True` or None to enable the new Dask Dataframe implementation and silence this warning.
  warnings.warn(

AnnData object with n_obs × n_vars = 98749 × 1024
    obs: 'cell_id', 'x_centroid', 'y_centroid', 'segmentation_method', 'fine_celltypes', 'broad_celltypes', 'region', 'celltype', 'DonorID', 'niche_name', 'info_id', 'Site_status', 'leiden_res1', 'leiden_res2', 'dataset_id', 'original_celltypes', 'n_counts', 'n_genes', 'inflow_CT', 'inflow_BatchID'
    uns: 'inflow_map_Batchname_to_inflowBatchID', 'inflow_map_CT_to_inflowCT'
    obsm: 'X_scarches', 'X_scvi', 'X_umap', 'inflow_mu_sin', 'inflow_mu_sout', 'inflow_mu_z', 'inflow_muxbar_int', 'inflow_muxbar_spl', 'inflow_muxint', 'inflow_muxint_before_sc_pp_normalize_total', 'inflow_muxspl', 'inflow_muxspl_before_sc_pp_normalize_total', 'spatial'
    layers: 'counts'

# DEGS

In [2]:
adata=sc.read_h5ad(BASE_DIR +  'adata_inflowOutput_norm.h5ad' )
adata

AnnData object with n_obs × n_vars = 98749 × 1024
    obs: 'cell_id', 'x_centroid', 'y_centroid', 'segmentation_method', 'fine_celltypes', 'broad_celltypes', 'region', 'celltype', 'DonorID', 'niche_name', 'info_id', 'Site_status', 'leiden_res1', 'leiden_res2', 'dataset_id', 'original_celltypes', 'n_counts', 'n_genes', 'inflow_CT', 'inflow_BatchID'
    uns: 'inflow_map_Batchname_to_inflowBatchID', 'inflow_map_CT_to_inflowCT'
    obsm: 'X_scarches', 'X_scvi', 'X_umap', 'inflow_mu_sin', 'inflow_mu_sout', 'inflow_mu_z', 'inflow_muxbar_int', 'inflow_muxbar_spl', 'inflow_muxint', 'inflow_muxint_before_sc_pp_normalize_total', 'inflow_muxspl', 'inflow_muxspl_before_sc_pp_normalize_total', 'spatial'
    layers: 'counts'

In [3]:
def remove_markers(LIST):
        try: 
            LIST = {key: [gene for gene in genes if gene in adata.var_names] 
                               for key, genes in LIST.items()}
        except: 
            LIST =[gene for gene in LIST if gene in adata_5k.var_names]
        return LIST


try:
    adata.obs["NICHE_NAMES"] = adata.obs["niche_name"]
except:
    adata


x_int = adata.obsm["inflow_muxint"]
x_spl = adata.obsm["inflow_muxspl"]   
key_celltype = "broad_celltypes" 
adata.obs.info_id.value_counts()

info_id
Melanoma    98749
Name: count, dtype: int64

# DEGs by population

In [3]:
# dict_ct_to_listmarker_ext, dict_ct_to_listmarker_int = {}, {}
# dict_ct_to_listmarker_ext, dict_ct_to_listmarker_int = {}, {}
# for ct in set(adata.obs[key_celltype]):
#     l_filter_ct = (adata.obs[key_celltype] == ct).tolist()
#     adata_ct = sc.AnnData(
#         X=np.concatenate([x_int[l_filter_ct, :], x_spl[l_filter_ct, :]], 0),
#         obs=pd.DataFrame(
#             data=np.array(
#                 [np.sum(l_filter_ct)*['intrinsic ({})'.format(ct)] + np.sum(l_filter_ct)*['extrinsic ({})'.format(ct)]]
#             ).T,
#             columns=['intrinsic_extrinsic']
#         ),
#         var=adata.var
#     )

#     #if flag_logaritmise:
#     sc.pp.log1p(adata_ct)

#     sc.tl.rank_genes_groups(adata_ct, 'intrinsic_extrinsic', method='wilcoxon')# n_genes=n_genes_showranking)
#     sc.pl.rank_genes_groups(adata_ct)

#     # grab the markers (to be used in the dot plots)
#     dict_ct_to_listmarker_ext[ct] = [
#         [u[0] for u in adata_ct.uns['rank_genes_groups']['names'].tolist()]
#     ]
    
#     dict_ct_to_listmarker_int[ct] = [
#         [u[1] for u in adata_ct.uns['rank_genes_groups']['names'].tolist()]
#     ]

In [2]:
# dict_ct_to_listmarker_ext, dict_ct_to_listmarker_int = {}, {}
# for ct in set(adata.obs[key_celltype]):
#     if ct=="T":
#         l_filter_ct = (adata.obs[key_celltype] == ct).tolist()
#         adata_ct = sc.AnnData(
#             X=np.concatenate([x_int[l_filter_ct, :], x_spl[l_filter_ct, :]], 0),
#             obs=pd.DataFrame(
#                 data=np.array(
#                     [np.sum(l_filter_ct)*['intrinsic ({})'.format(ct)] + np.sum(l_filter_ct)*['extrinsic ({})'.format(ct)]]
#                 ).T,
#                 columns=['intrinsic_extrinsic']
#             ),
#             var=adata.var
#         )

#         #if flag_logaritmise:
#         sc.pp.log1p(adata_ct)

#         sc.tl.rank_genes_groups(adata_ct, 'intrinsic_extrinsic', method='wilcoxon')# n_genes=n_genes_showranking)
#         sc.pl.rank_genes_groups(adata_ct)

#         # grab the markers (to be used in the dot plots)
#         dict_ct_to_listmarker_ext[ct] = [
#             [u[0] for u in adata_ct.uns['rank_genes_groups']['names'].tolist()]
#         ]
#         dict_ct_to_listmarker_int[ct] = [
#             [u[1] for u in adata_ct.uns['rank_genes_groups']['names'].tolist()]
#         ]

In [4]:
# ALL_T = {'Conventional': ['CD3D', "CD4", "CD8A"],
#               'Treg': ['FOXP3', 'TIGIT', 'CTLA4', ],
#          "Activated_Treg": ["LRRC32", "IL1R1","IL1R2",'TRAF3',  "ITGAV",
#                             #'CMSS1', 'LRRC32',
#                             'F5',# "TOX"
#                            'ZNF331', 'JMY', 'ELL2','NR4A3','NR4A1','BICDL1',

#                            ],
#               'TR1': ['EOMES', 'IL10', 'LAG3', 'HAVCR2', "PDCD1", 'FOXB1'],
#  'Naive/Tcm': ['SELL', 'CCR7', 'S1PR1', 'TCF7', "PAK2"],
#  'Th': ['CD40LG', "MCAM", "CCR6", "BACH2"],
#  'CD8A+ cytotoxic T cells': ['CD8A', 'GZMK', 'IFNG', 'TNFSF9',"CXCR3",# "MCOLN1"
#                             ],
#          "Cytotoxic": [ "NKG7","CCL5","GZMA",  ],
#          "Tissue-residency\n markers": ["ITGAE",  'ZNF683', "ENTPD1",  "RBPJ"],
# 'IL22': ['IL22', 'IL13', 'PDLIM4', #'KRT7',
#          "NBAS",  'CCL1', "CCL17", "AREG", "CCR8", "CCR10"],
#  'T_17': [ 'IL17A', 'IL17F', 'CXCL13', 'IL26', "IL21", 'CCL20', 'CTSH', "IL23R","ITGA1", 
#          "CCR6","RORC", 'TNFRSF8', "ADAM12", "IL1R1", "IL12RB2"],
#          #"Memory": ["CD69",],
#               'Gamma-delta': ["FXYD2", "TRGC2", 'TRDV1','TRGV4',  "EMP1",
#                              "NSG1", #"LINC02446","CD9", 
#                               "MPZL2", "KLRC2"], #'TRGC2', 
#              "Innate": ["KLRB1", "KIT", "KLRC1", "KLRC2", 'KLRC3', "TYROBP", "FCER1G",],
               
#                "NK": [ "TBX21",#
#                       "NCR1",#'NMUR1', "NMU",
#                       "B3GAT1", 
#                       "PTGDS",
#                       "CX3CR1", # 
#                       "CCL4L2", #
#                     #
#                       "PRSS23", "CD160", #
#                       "KLRF1", "KLRG1","S100B",
                             
#                       #"CD160", "PLEK", "NMUR1", "IL12RB1", "FGFBP2", "FCGR3A", "GZMH","AKR1C3","FGR", "CD38", 
#                      # "LAIR2", "SPON2", "S1PR5","FCRL6","PRF1", 
#                               ],
#                       "NK+ILC1": ["KLRD1","NCAM1", "PRF1"  #"IL15",
#                                  ],
#    'ILC1_NK': [ "IRF8",# 'GZMK', "IGFBP4",  "TCF7"
#                #"IL18", 
#                "ADGRG3", #"CXCR3",
#               ],
#                "ILC1/3": [ "XCL1", "XCL2", "CSF2", "KRT86" ],

#                "ILC3": ["ID3", #"ZNF683",
#                         "ZBTB46", "TNFSF4", "SPINK2", "RAMP1", "MB", "KLRF2", "TMPRSS11E", #"CAMK1", "PECAM1"
#                        ], #'TNF', "CCR8", "CD9"],

#                 "ILC2+3": ["IL9R", "TNFSF11"],
#  'ILC2': ['GATA3',  "PTGDR2", "TNFRSF25",# "BCL11B", "MAF", 
#           #"CALCRL", "HPGDS" ,  "S1PR1",
#          ],
#       'ILC2_inflammatory': [ "CRLF2", "IL17RB", "IL1RL1" , #"IL4", "IL13",'TNFRSF9',
#                             "IL18R1", "PPARG",
#                             "PTGS2", #"NBAS",# "PDLIM5", "MCAM", 
#                             "PLA2G4A", "IL4", "IL31",
#                            "ICOS", "NRROS"
#                            ],
#          "Cycling": ['UBE2C', 'MKI67', "TOP2A",# "BIRC5",
#                                 #  "MYBL2", "TPX2"
#                                   ], 
#                }




# sc.pl.dotplot(adata_ct, 
#               remove_markers(ALL_T),
#               groupby=f'intrinsic_extrinsic',
#               dendrogram=False, 
#                # standard_scale="var",
#              dot_max=0.3,)



# sc.pl.dotplot(adata_ct, 
#               remove_markers(ALL_T),
#               groupby=f'intrinsic_extrinsic',
#               dendrogram=False, 
#                 standard_scale="var",
#              dot_max=0.3,)

# sc.pl.dotplot(adata_ct, 
#               remove_markers(ALL_T),
#               groupby=f'intrinsic_extrinsic',
#               dendrogram=False, 
#                 standard_scale="var",
#              dot_max=0.3,)

In [5]:
# dict_ct_to_listmarker_ext, dict_ct_to_listmarker_int = {}, {}
# for ct in set(adata.obs[key_celltype]):
#     if ct=="F6: Myofibroblast inflammatory":
#         l_filter_ct = (adata.obs[key_celltype] == ct).tolist()
#         adata_ct = sc.AnnData(
#             X=np.concatenate([x_int[l_filter_ct, :], x_spl[l_filter_ct, :]], 0),
#             obs=pd.DataFrame(
#                 data=np.array(
#                     [np.sum(l_filter_ct)*['intrinsic ({})'.format(ct)] + np.sum(l_filter_ct)*['extrinsic ({})'.format(ct)]]
#                 ).T,
#                 columns=['intrinsic_extrinsic']
#             ),
#             var=adata.var
#         )

#         #if flag_logaritmise:
#         sc.pp.log1p(adata_ct)

#         sc.tl.rank_genes_groups(adata_ct, 'intrinsic_extrinsic', method='wilcoxon')# n_genes=n_genes_showranking)
#         sc.pl.rank_genes_groups(adata_ct)

#         # grab the markers (to be used in the dot plots)
#         dict_ct_to_listmarker_ext[ct] = [
#             [u[0] for u in adata_ct.uns['rank_genes_groups']['names'].tolist()]
#         ]
#         dict_ct_to_listmarker_int[ct] = [
#             [u[1] for u in adata_ct.uns['rank_genes_groups']['names'].tolist()]
#         ]

In [8]:

# pickle_file_path = '/nfs/team298/ls34/fb_dict.pkl'

# with open(pickle_file_path, 'rb') as file:
#     reynolds_short_final = pickle.load(file)


# pickle_file_path = '/nfs/team298/ls34/fb_dict_lesional.pkl'

# with open(pickle_file_path, 'rb') as file:
#     LESIONAL = pickle.load(file)

    
# FBS = {'F1': ['APCDD1',
#   'COL18A1',
#   'COL23A1',
#   'COL13A1',
#   'COMP',
#   'NKD2',
#   'RSPO1',
#   'AXIN2',
#   'WIF1',
#   'SFRP2'],
#                     "Activated F1": [ 'CRABP1',
#   'TNFRSF21',
#   'CXCL1'],
#                    'F1+F6:My_Inf': ['WNT5A', 'COL7A1'],
#  'F2: Universal': ['CD34',
#   'PI16',
#   'DPP4',
#   'MFAP5',
#   'PCOLCE2',
#   'CTHRC1',
#   'SLPI',
#   'CD70',
#   'LGR5'],
#  'F2/3: Bridge': ['CXCL12',
#   'APOE',
#   'EFEMP1',
#   'APOC1',
#   'C7',
#   'PLA2G2A',
#   'PPARG',
#   'MYOC',
#   'GDF10'],
#  'F3': ['CCL19',
#   'CD74',
#   'CH25H',
#   'TNFSF13B',
#   'IL33',
#   'IRF8',
#   'IL15',
#   'VCAM1',
#   'HLA-DRA',
#   'HLA-DRB1'],
#           "Activated F3": ["ADAMDEC1", "CXCL9", "CXCL10"],
#  'F4': ['ASPN'],
#  'F4: DS_DPEP1+': ['COL11A1', 'MEF2C', 'DPEP1', 'MYL4'],
#  'F4: TNN+COCH+': ['TNN',
#   'COCH',
#   'CRABP1',
#   'COL24A1',
#   'RSPO4',
#   'SLITRK6',
#   'NRG3',
#   'MKX',
#   'TNMD'],
#  'F4: DP_HHIP+': ['CORIN',
#   'BMP7',
#   'WNT5A',
#   'LEF1',
#   'HHIP',
#   'RSPO3',
#   'INHBA',
#   'PTCH1'],
#  'F5': ['SCN7A', 'FMO2', 'FGFBP2', 'OLFML2A'],
#  'F5+: RAMP1': ['RAMP1', 'RELN', 'PLEKHA6', 'IGFBP2', 'SFRP1'],
#  'F5: NGFR+': ['EBF2', 'NGFR', 'SFRP4', 'ITGA6', 'CDH19', 'CLDN1'],
# 'F6: Myofibroblast inflammatory': ['CXCL8',
#   'CXCL5',
#   'CXCL6',
#   'CXCL13',
#   'IL11',
#   'IL24',
#   'MMP1',
#   'MMP3',
#   'IL7R',
#   'INHBA',
#   'CSF3',
#   'TDO2',
#   'WWC1',
#   'CHI3L1',
#   'STAT4',
#   'CCL5',
#   'CCL3',
#   'CCL11'],
#  'F6 (both)': ['WNT2', 'COL10A1', 'LAMP5'],
         
#          }




# sc.pl.dotplot(adata_ct, 
#               remove_markers(FBS),
#               groupby=f'intrinsic_extrinsic',
#               dendrogram=False, 
#                 standard_scale="var",
#              dot_max=0.3,)


# # sc.pl.dotplot(adata_i, 
# #               remove_markers(FBS),
# #               groupby=f'spatial_niche',
# #               dendrogram=False, 
# #                 standard_scale="var",
# #              dot_max=0.3,)
# sc.pl.dotplot(adata_ct, 
#               remove_markers(LESIONAL),
#               groupby=f'intrinsic_extrinsic',
#               dendrogram=False, 
#                 standard_scale="var",
#              dot_max=0.3,)

# sc.pl.dotplot(adata_ct, 
#               remove_markers(["LOX", "COL1A1", "COL3A1", "COL5A1", "LOXL", "HIF1A", "TNC"]),
#               groupby=f'intrinsic_extrinsic',
#               dendrogram=False, 
#                # standard_scale="var",
#              dot_max=0.3,)

# MMPS = [x for x in adata_ct.var_names if x.startswith("MMP")]
# sc.pl.dotplot(adata_ct, 
#               remove_markers(MMPS),
#               groupby=f'intrinsic_extrinsic',
#               dendrogram=False, 
#                 standard_scale="var",
#              dot_max=0.3,)
# # sc.pl.dotplot(adata_i, 
# #               remove_markers(LESIONAL),
# #               groupby=f'spatial_niche',
# #               dendrogram=False, 
# #                 standard_scale="var",
# #              dot_max=0.3,)

# Use PCA as only 1 sample

In [9]:
M_BAR_METRIC='inflow_muxbar_spl'
adata.layers["xint"]=x_int#adata.obsm["pred_Xint"].copy()
adata.layers["xspl"]=x_spl#adata.obsm["pred_Xspl"].copy()

In [10]:
try:
    del(adata.obsm["X_pca"])
except:
    print("no x_pca present ")

no x_pca present

In [11]:
if "spl" in M_BAR_METRIC:
    LAYER = "xspl"
else:
    LAYER = "xint"
print(LAYER)

xspl

In [12]:
sc.pp.pca(adata, n_comps=30, layer=LAYER)

In [13]:
sc.pp.neighbors(adata, use_rep = 'X_pca', 
                metric = "euclidean", n_neighbors=30)#key_added=neighbor_id)

In [14]:
sc.tl.umap(adata, min_dist=0.3) #neighbor_key=)

In [15]:
RES=0.5
sc.tl.leiden(adata, #restrict_to=(CATEGORY,subset_cluster), 
             resolution=RES, random_state=1, key_added=f'leiden_res{RES}') #neighbors_key='neighbor_30')

/tmp/ipykernel_1019/216381242.py:2: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.
  sc.tl.leiden(adata, #restrict_to=(CATEGORY,subset_cluster),

# Label clusters based on composition

In [16]:
top_n = 9
GROUP =  f"leiden_res{RES}"

grouped_data = (
    adata.obs.groupby([GROUP, key_celltype])
    .size()
    .reset_index(name="count")
)

grouped_data["total_count"] = grouped_data.groupby(GROUP)["count"].transform("sum")
grouped_data["percentage"] = round((grouped_data["count"] / grouped_data["total_count"]) * 100)
sorted_data = grouped_data.sort_values(
    [GROUP, "count"], ascending=[True, False]
)

top_contributors = sorted_data.groupby(GROUP).head(top_n)

top_contributors

/tmp/ipykernel_1019/3944751648.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  adata.obs.groupby([GROUP, key_celltype])
/tmp/ipykernel_1019/3944751648.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped_data["total_count"] = grouped_data.groupby(GROUP)["count"].transform("sum")
/tmp/ipykernel_1019/3944751648.py:16: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  top_contributors = sorted_data.groupby(GROUP).head(top_n)

,leiden_res0.5,broad_celltypes,count,total_count,percentage
11,0,Melanoma,42176,45144,93.0
16,0,T,1237,45144,3.0
9,0,Mac,1236,45144,3.0
1,0,F6: Myofibroblast,328,45144,1.0
3,0,KCinflamm_basal,25,45144,0.0
10,0,Mast cell,25,45144,0.0
13,0,Nonspecific,23,45144,0.0
15,0,Plasma cell,22,45144,0.0
14,0,Pericyte,21,45144,0.0
36,1,T,9189,14273,64.0
29,1,Mac,2504,14273,18.0
31,1,Melanoma,723,14273,5.0
39,1,cDC2,452,14273,3.0
32,1,MigDC,313,14273,2.0
35,1,Plasma cell,224,14273,2.0
21,1,F6: Myofibroblast,209,14273,1.0
37,1,VE,106,14273,1.0
30,1,Mast cell,105,14273,1.0
49,2,Mac,10896,13742,79.0
59,2,cDC2,1214,13742,9.0
56,2,T,725,13742,5.0
42,2,F6: Myofibroblast inflammatory,320,13742,2.0
41,2,F6: Myofibroblast,221,13742,2.0
55,2,Plasma cell,100,13742,1.0
51,2,Melanoma,62,13742,0.0
52,2,MigDC,55,13742,0.0
54,2,Pericyte,36,13742,0.0
62,3,F6: Myofibroblast inflammatory,3914,9554,41.0
61,3,F6: Myofibroblast,3089,9554,32.0
76,3,T,1196,9554,13.0
60,3,F1: Superficial,722,9554,8.0
74,3,Pericyte,146,9554,2.0
69,3,Mac,119,9554,1.0
75,3,Plasma cell,97,9554,1.0
79,3,cDC2,87,9554,1.0
70,3,Mast cell,44,9554,0.0
97,4,VE,2516,5078,50.0
94,4,Pericyte,1957,5078,39.0
96,4,T,207,5078,4.0
81,4,F6: Myofibroblast,104,5078,2.0
88,4,LE,84,5078,2.0
82,4,F6: Myofibroblast inflammatory,72,5078,1.0
80,4,F1: Superficial,66,5078,1.0
99,4,cDC2,21,5078,0.0
89,4,Mac,17,5078,0.0
111,5,Melanoma,3433,4059,85.0
116,5,T,252,4059,6.0
109,5,Mac,219,4059,5.0
101,5,F6: Myofibroblast,43,4059,1.0
113,5,Nonspecific,32,4059,1.0
115,5,Plasma cell,16,4059,0.0
119,5,cDC2,13,4059,0.0
103,5,KCinflamm_basal,9,4059,0.0
117,5,VE,9,4059,0.0
135,6,Plasma cell,3149,3534,89.0
136,6,T,171,3534,5.0
122,6,F6: Myofibroblast inflammatory,84,3534,2.0
129,6,Mac,54,3534,2.0
121,6,F6: Myofibroblast,32,3534,1.0
131,6,Melanoma,9,3534,0.0
130,6,Mast cell,7,3534,0.0
134,6,Pericyte,7,3534,0.0
138,6,cDC1,6,3534,0.0
145,7,KCinflamm_int,1108,3365,33.0
143,7,KCinflamm_basal,977,3365,29.0
146,7,KCinflamm_late,612,3365,18.0
144,7,KCinflamm_final,194,3365,6.0
156,7,T,156,3365,5.0
149,7,Mac,84,3365,2.0
151,7,Melanoma,45,3365,1.0
152,7,MigDC,35,3365,1.0
157,7,VE,23,3365,1.0

In [17]:
RENAME = {'0': "Melanoma1", 
          '1': "Melanoma1", 
          '2': "T_hub", 
          '3': "Mac_hub", 
          '4': "Stroma",
          '5': "Perivascular", 
          '6': "Melanoma2", 
          '7': "Plasma cell hub", 
          '8': "Epidermis"}

adata.obs[f'spatial_niche'] = adata.obs[f'leiden_res{RES}'].map(RENAME)

In [18]:
top_n = 9
GROUP =  f"spatial_niche"


grouped_data = (
    adata.obs.groupby([GROUP, key_celltype])
    .size()
    .reset_index(name="count")
)

grouped_data["total_count"] = grouped_data.groupby(GROUP)["count"].transform("sum")
grouped_data["percentage"] = round((grouped_data["count"] / grouped_data["total_count"]) * 100)
sorted_data = grouped_data.sort_values(
    [GROUP, "count"], ascending=[True, False]
)

top_contributors = sorted_data.groupby(GROUP).head(top_n)

top_contributors

/tmp/ipykernel_1019/212764156.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  adata.obs.groupby([GROUP, key_celltype])

,spatial_niche,broad_celltypes,count,total_count,percentage
2,Mac_hub,F6: Myofibroblast inflammatory,3914,9554,41.0
1,Mac_hub,F6: Myofibroblast,3089,9554,32.0
16,Mac_hub,T,1196,9554,13.0
0,Mac_hub,F1: Superficial,722,9554,8.0
14,Mac_hub,Pericyte,146,9554,2.0
9,Mac_hub,Mac,119,9554,1.0
15,Mac_hub,Plasma cell,97,9554,1.0
19,Mac_hub,cDC2,87,9554,1.0
10,Mac_hub,Mast cell,44,9554,0.0
31,Melanoma1,Melanoma,42899,59417,72.0
36,Melanoma1,T,10426,59417,18.0
29,Melanoma1,Mac,3740,59417,6.0
21,Melanoma1,F6: Myofibroblast,537,59417,1.0
39,Melanoma1,cDC2,469,59417,1.0
32,Melanoma1,MigDC,317,59417,1.0
35,Melanoma1,Plasma cell,246,59417,0.0
30,Melanoma1,Mast cell,130,59417,0.0
34,Melanoma1,Pericyte,124,59417,0.0
55,Melanoma2,Plasma cell,3149,3534,89.0
56,Melanoma2,T,171,3534,5.0
42,Melanoma2,F6: Myofibroblast inflammatory,84,3534,2.0
49,Melanoma2,Mac,54,3534,2.0
41,Melanoma2,F6: Myofibroblast,32,3534,1.0
51,Melanoma2,Melanoma,9,3534,0.0
50,Melanoma2,Mast cell,7,3534,0.0
54,Melanoma2,Pericyte,7,3534,0.0
58,Melanoma2,cDC1,6,3534,0.0
71,Perivascular,Melanoma,3433,4059,85.0
76,Perivascular,T,252,4059,6.0
69,Perivascular,Mac,219,4059,5.0
61,Perivascular,F6: Myofibroblast,43,4059,1.0
73,Perivascular,Nonspecific,32,4059,1.0
75,Perivascular,Plasma cell,16,4059,0.0
79,Perivascular,cDC2,13,4059,0.0
63,Perivascular,KCinflamm_basal,9,4059,0.0
77,Perivascular,VE,9,4059,0.0
85,Plasma cell hub,KCinflamm_int,1108,3365,33.0
83,Plasma cell hub,KCinflamm_basal,977,3365,29.0
86,Plasma cell hub,KCinflamm_late,612,3365,18.0
84,Plasma cell hub,KCinflamm_final,194,3365,6.0
96,Plasma cell hub,T,156,3365,5.0
89,Plasma cell hub,Mac,84,3365,2.0
91,Plasma cell hub,Melanoma,45,3365,1.0
92,Plasma cell hub,MigDC,35,3365,1.0
97,Plasma cell hub,VE,23,3365,1.0
117,Stroma,VE,2516,5078,50.0
114,Stroma,Pericyte,1957,5078,39.0
116,Stroma,T,207,5078,4.0
101,Stroma,F6: Myofibroblast,104,5078,2.0
108,Stroma,LE,84,5078,2.0
102,Stroma,F6: Myofibroblast inflammatory,72,5078,1.0
100,Stroma,F1: Superficial,66,5078,1.0
119,Stroma,cDC2,21,5078,0.0
109,Stroma,Mac,17,5078,0.0
129,T_hub,Mac,10896,13742,79.0
139,T_hub,cDC2,1214,13742,9.0
136,T_hub,T,725,13742,5.0
122,T_hub,F6: Myofibroblast inflammatory,320,13742,2.0
121,T_hub,F6: Myofibroblast,221,13742,2.0
135,T_hub,Plasma cell,100,13742,1.0
131,T_hub,Melanoma,62,13742,0.0
132,T_hub,MigDC,55,13742,0.0
134,T_hub,Pericyte,36,13742,0.0

In [19]:
{x:x for x in adata.obs['spatial_niche'].unique()}

{'Plasma cell hub': 'Plasma cell hub',
 'Melanoma1': 'Melanoma1',
 'Perivascular': 'Perivascular',
 'Stroma': 'Stroma',
 'T_hub': 'T_hub',
 'Mac_hub': 'Mac_hub',
 'Melanoma2': 'Melanoma2'}

In [ ]:
COLORS = {'Epidermis': '#0000FF',
 'T_hub': '#F4D1A1',
 'Melanoma2': '#A9A9A9', #BROWN = 5C4033
 'Perivascular': '#d73435',
 'Mac_hub': '#4B0082',
 'Melanoma1': '#000000',
 'Stroma': '#FFFF00',
 'Plasma cell hub': '#4DFFFF'}



adata.obs['spatial_niche']=adata.obs['spatial_niche'].astype('category')
adata.uns['spatial_niche_colors'] = [COLORS[cat] for cat in adata.obs['spatial_niche'].cat.categories]

# sc.pl.umap(
#     adata,
#     color=['spatial_niche'],
#     s=5,
#     legend_loc="on data",
#     legend_fontsize=18,
#     legend_fontoutline=2,
#             edgecolor="black",
#         linewidth=0.1,
# )
# sc.pl.umap(
#     adata,
#     color=['spatial_niche'],
#     s=10,
#     legend_loc="on data",
#     legend_fontsize=18,
#     legend_fontoutline=2,
#             edgecolor="black",
#         linewidth=0.1,
#     save="spatial_umap_mm.pdf",
#     title=""
# )

In [21]:
# adata.write('/nfs/team361/ls34/inflow/adata_mm_spatial_finalv.h5ad')

In [22]:
STOP

NameError: name 'STOP' is not defined

# Data prepared

In [ ]:
import scanpy as sc
import os
import os, sys
import scipy
import pandas as pd
import scanpy as sc
# import dask
import squidpy as sq
import matplotlib.pyplot as plt
import numpy as np

import pickle

adata=sc.read_h5ad('/nfs/team361/ls34/inflow/adata_mm_spatial_finalv.h5ad')

In [ ]:
key_celltype="broad_celltypes"

In [ ]:
sc.settings.set_figure_params(dpi=300, facecolor="white", frameon=False, figsize=(14,14))

sc.pl.umap(
    adata,
    color=['spatial_niche'],
    s=50,
    legend_loc="on data",
    legend_fontsize=18,
    legend_fontoutline=2,
            edgecolor="black",
        linewidth=0.1,
    save="spatial_umap_mm.pdf",
    title=""
)

In [ ]:
sq.pl.spatial_scatter(
        adata,
        library_id="spatial",
        shape=None,
        color=f'spatial_niche',
        size=5,
        title='',
    save="spatial_by_space.pdf"
    )

In [ ]:
sq.pl.spatial_scatter(
        adata,
        library_id="spatial",
        shape=None,
        color=['CXCL12', "CCL19"],
        size=1,
        title='',
        vmax=20,
    save="cxcl19_ccl19_umap.pdf"
    )

In [ ]:
sq.pl.spatial_scatter(
        adata,
        library_id="spatial",
        shape=None,
        color=['MLANA', 'SOX10', 'PRAME', "MELTF"],
        size=1,
        title='',
        vmax=20,
    save="Melanoma_degs_by_space_toprow.pdf"
    )

In [ ]:
sq.pl.spatial_scatter(
        adata,
        library_id="spatial",
        shape=None,
        color=['EDNRB', 'CST1', 'BAALC', "GDF15"],
        size=1,
        title='',
        vmax=20,
    save="Melanoma_degs_by_space_bottomrow.pdf"
    )

In [ ]:
import pandas as pd
CATEGORY = 'spatial_niche'
ADATA = adata

sc.tl.rank_genes_groups(adata, CATEGORY, method='t-test', key_added="de_leiden");
df2 = pd.DataFrame(adata.uns['de_leiden']['names'])
for i,x in enumerate(df2.columns):
     print(i,":",x)

In [ ]:
# select_population = list(df2.columns)[4
#                                      ]
# print(select_population)

# genes0 = df2[select_population][:50]
# genes1 = df2[select_population][50:100]
# genes2 = df2[select_population][100:150]
# genes3 = df2[select_population][150:200]
# genes4 = df2[select_population][200:250]
# genes5 = df2[select_population][250:300]
# genes6 = df2[select_population][300:350]
# genes7 = df2[select_population][350:400]
# genes8 = df2[select_population][400:450]

# result = adata.uns['de_leiden']
# groups = result['names'].dtype.names
# groups = ["Melanoma2"]
# marker_genes = pd.DataFrame({group: result['names'][group] for group in groups})
# #marker_genes

In [ ]:
# import gseapy as gp

# # Display the marker genes DataFrame
# print(marker_genes.head())

# # Perform GSEA for each cluster
# for cluster in marker_genes.columns:
#     gene_list = marker_genes[cluster].tolist()
#     enr = gp.enrichr(gene_list=gene_list[:500],
#                      #description=f'Cluster_{cluster}',
#                      gene_sets='GO_Biological_Process_2023',  #'GO_Biological_Process_2021' # You can choose other gene sets here
#                      outdir='GSEA_plots',  # Directory to save results
#                      cutoff=0.05  # Cutoff for statistical significance
#                     )
#     # Print the results
#     print(enr.results.head())

# import scanpy as sc
# import pandas as pd
# import gseapy as gp
# import matplotlib.pyplot as plt
# import seaborn as sns

# # Assuming adata_subset is already defined and contains the data

# result = adata_core.uns['rank_genes_groups']
# groups = result['names'].dtype.names
# marker_genes = pd.DataFrame({group: result['names'][group] for group in groups})

# # Perform GSEA for each cluster and collect results
# gsea_results = []

# for cluster in marker_genes.columns:
#     gene_list = marker_genes[cluster].tolist()
#     enr = gp.enrichr(gene_list=gene_list[:100],
#                      gene_sets='GO_Biological_Process_2023',  # You can choose other gene sets here
#                      outdir=None,  # Set to None to avoid creating output files
#                      cutoff=0.05  # Cutoff for statistical significance
#                     )
#     enr.results['Cluster'] = cluster
#     gsea_results.append(enr.results)

# # Combine all results into a single DataFrame
# gsea_df = pd.concat(gsea_results)

# """

# Reactome_2019 
# 'GO_Biological_Process_2018''GO_Cellular_Component_2018''GO_Molecular_Function_2018'
# """


# # Select top 10 enriched pathways for each cluster
# top_gsea_df = gsea_df.groupby('Cluster').apply(lambda x: x.nlargest(4, 'Combined Score')).reset_index(drop=True)

# # Plotting
# plt.figure(figsize=(15, 10))
# sns.barplot(x='Combined Score', y='Term', hue='Cluster', data=top_gsea_df, dodge=False)
# plt.title('Top 10 Enriched KEGG Pathways per Cluster')
# plt.xlabel('Combined Score')
# plt.ylabel('Pathway')
# plt.legend(title='Cluster')
# plt.tight_layout()
# plt.show()

# import matplotlib.pyplot as plt
# import seaborn as sns

# # Assuming color_palettes is a dictionary where the keys are clusters and values are colors
# # Example: color_palettes = {'Cluster1': '#FF6347', 'Cluster2': '#4682B4', ...}

# # Select top 10 enriched pathways for each cluster
# top_gsea_df = gsea_df.groupby('Cluster').apply(lambda x: x.nlargest(4, 'Combined Score')).reset_index(drop=True)

# # Sort the DataFrame so that terms are grouped by cluster
# top_gsea_df = top_gsea_df.sort_values(by=['Cluster', 'Combined Score'], ascending=[True, False])

# # Create a list of colors based on the Cluster column, using the color_palettes dictionary
# cluster_colors = top_gsea_df['Cluster'].map(color_palettes)

# # Plotting
# plt.figure(figsize=(20, 20))
# sns.barplot(x='Combined Score', y='Term', hue='Cluster', data=top_gsea_df, palette=color_palettes, dodge=False)
# plt.title('Top 10 Enriched KEGG Pathways per Cluster', fontsize=14)
# plt.xlabel('Combined Score', fontsize=12)
# plt.ylabel('Pathway', fontsize=12)
# plt.xticks(fontsize=10)
# plt.yticks(fontsize=10)
# plt.legend(title='Cluster', bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=10, title_fontsize='13')
# plt.tight_layout()
# plt.show()

In [ ]:
DEGS = []
for select_population in list(df2.columns):
    print(select_population)

    genes0 = list(df2[select_population][:10])
    DEGS.extend(genes0)
# genes1 = df2[select_population][50:100]
# genes2 = df2[select_population][100:150]
# genes3 = df2[select_population][150:200]
# genes4 = df2[select_population][200:250]
# genes5 = df2[select_population][250:300]
# genes6 = df2[select_population][300:350]
# genes7 = df2[select_population][350:400]
# genes8 = df2[select_population][400:450]
 
# genes14 = df2[select_population][700:750]
# genes15 = df2[select_population][750:800]
# genes16 = df2[select_population][800:850]
# genes17 = df2[select_population][850:900]
# genes18 = df2[select_population][900:950]
# genes19 = df2[select_population][950:1000]
# genes20 = df2[select_population][1000:1050]
# genes21 = df2[select_population][1050:1100]
# genes22 = df2[select_population][1100:1150]
# genes23 = df2[select_population][1150:1200]
# genes24 = df2[select_population][1200:1250]
# genes25 = df2[select_population][1250:1300]
# genes26 = df2[select_population][1300:1350]
# genes27 = df2[select_population][1350:1400]

# # Define the desired order for the CATEGORY
# category_order = ['Lesional Baseline', 'Day 3', 'Day 14', 'Week 12', 'Non-lesional Baseline']

# # Ensure the CATEGORY column in adata has the desired order
# adata_i.obs[CATEGORY] = pd.Categorical(adata_i.obs[CATEGORY], categories=category_order, ordered=True)

# # Now, generate each dot plot with the specified order applied

sc.pl.matrixplot(
    ADATA,
    DEGS,
    groupby=CATEGORY,
    standard_scale="var",
    dendrogram=False,
    cmap="Reds",
        save="spatial_degs.pdf"

)

#     sc.pl.dotplot(
#         ADATA,
#         genes1,
#         groupby=CATEGORY,
#         standard_scale="var",
#         dendrogram=False,
#     )


#     sc.pl.dotplot(
#         adata,
#         genes0,
#         groupby=key_celltype,
#         standard_scale="var",
#         dendrogram=False,
#     )

#     sc.pl.dotplot(
#         adata,
#         genes1,
#         groupby=key_celltype,
#         standard_scale="var",
#         dendrogram=False,
#     )

In [ ]:
select_population = list(df2.columns)[-2
                                     ]
CATEGORY="spatial_niche"
print(select_population)

genes0 = df2[select_population][:50]
genes1 = df2[select_population][50:100]
genes2 = df2[select_population][100:150]
genes3 = df2[select_population][150:200]
genes4 = df2[select_population][200:250]
genes5 = df2[select_population][250:300]
genes6 = df2[select_population][300:350]
genes7 = df2[select_population][350:400]
genes8 = df2[select_population][400:450]
 
# genes14 = df2[select_population][700:750]
# genes15 = df2[select_population][750:800]
# genes16 = df2[select_population][800:850]
# genes17 = df2[select_population][850:900]
# genes18 = df2[select_population][900:950]
# genes19 = df2[select_population][950:1000]
# genes20 = df2[select_population][1000:1050]
# genes21 = df2[select_population][1050:1100]
# genes22 = df2[select_population][1100:1150]
# genes23 = df2[select_population][1150:1200]
# genes24 = df2[select_population][1200:1250]
# genes25 = df2[select_population][1250:1300]
# genes26 = df2[select_population][1300:1350]
# genes27 = df2[select_population][1350:1400]

# # Define the desired order for the CATEGORY
# category_order = ['Lesional Baseline', 'Day 3', 'Day 14', 'Week 12', 'Non-lesional Baseline']

# # Ensure the CATEGORY column in adata has the desired order
# adata_i.obs[CATEGORY] = pd.Categorical(adata_i.obs[CATEGORY], categories=category_order, ordered=True)

# # Now, generate each dot plot with the specified order applied

# sc.pl.dotplot(
#     ADATA,
#     genes0,
#     groupby=CATEGORY,
#     standard_scale="var",
#     dendrogram=False,
# )

sc.pl.matrixplot(
    ADATA,
    genes0,
    groupby=CATEGORY,
    standard_scale="var",
    dendrogram=False,
    cmap="Reds",
        save="spatial_MCP_stroma.pdf"

)

In [ ]:
sc.pl.dotplot(
    ADATA,
    ["CXCL12", "CCL19"],
    groupby="spatial_niche",
    standard_scale="var",
    dendrogram=False,
    cmap="Reds",
        save="DOTPLOT_CXCL12_CCL19.pdf"

)

In [ ]:
KEEP = [#'KCinflamm_late',
# 'KCinflamm_final',
 #'KCinflamm_int',
 #'KCinflamm_basal',
 'cDC2',
 'LC',
 'T',
 'Mast cell',
 #'Melanoma',
 #'F6: Myofibroblast inflammatory',
 #'F1: Superficial',
 'Mac',
 #'Nonspecific',
 'Plasma cell',
 #'Pericyte',
 'cDC1',
 #'LE',
 #'F6: Myofibroblast',
 #'VE',
 'MigDC']
adata_immune = adata[adata.obs[key_celltype].isin(KEEP)]
sc.pl.dotplot(
    adata_immune,
    ["CXCL12", "CCL19"],
    groupby=key_celltype,
    standard_scale="var",
    dendrogram=False,
    cmap="Reds",
        save="DOTPLOT_CXCL12_CCL19_immunecells.pdf"

)

In [ ]:
# sc.pl.dotplot(
#     ADATA,
#     ["CXCL12", "CCL19"],
#     groupby="spatial_niche",
#     standard_scale="var",
#     dendrogram=False,
#     cmap="Reds",
#         save="DOTPLOT_CXCL12_CCL19.pdf"

# )

In [ ]:
list(adata.obs[key_celltype].unique())

In [ ]:
{x:x for x in ADATA.obs[key_celltype].unique()}

In [ ]:
# colors = {'KCinflamm_late': '#b1dae6',
#  'KCinflamm_final': '#c8cada',
#  'KCinflamm_int': '#839edd',
#  'KCinflamm_basal': '#505aa1',
#  'cDC2': '#6F478C',
#  'LC': '#5F3D7D',
#  'T': '#F5A600',
#  'Mast cell': '#FF1493',
#  'Melanoma': '#5C4033',
#  'F6: Myofibroblast inflammatory': '#00ffff',
#  'F1: Superficial': '#FFFFE4',
#  'Mac': '#845DAE',
#  'Nonspecific': '#D3D3D3',
#  'Plasma cell': '#ff5e00',
#  'Pericyte': '#F7A3C3',
#  'cDC1': '#9B70C1',
#  'LE': '#FFFF00',
#  'F6: Myofibroblast': '#1E3A5F',
#  'VE': '#d73435',
#  'MigDC': '#00FF00'}

colors  = {'KCinflamm_late': '#f4e9ef',
 'KCinflamm_final': '#E07090',
 'KCinflamm_int': '#007FFF',
 'KCinflamm_basal': '#f4e9ef',
 'cDC2': '#6F478C',
 'LC': '#3bc1d9',
 'T': '#F4D1A1',
 'Mast cell': '#FF5F00',
 'Melanoma': '#3D1C02',
 #'F6: Myofibroblast inflammatory': 'Cancer-associated fibroblast',
 'Fibroblast': '#FFFFE4',
 'Mac': '#1B03A3',
 'Nonspecific': '#D3D3D3',
 'Plasma cell': '#ff5e00',
 'Pericyte': '#F7A3C3',
 'cDC1': '#9B70C1',
 'LE': '#FFFF00',
 'Cancer-associated fibroblast':"#52aaff" ,
 'VE': '#d73435',
 'MigDC': '#00FF00'}

In [ ]:
ADATA.obs["spatial_niche"].unique()

In [ ]:
RENAME = {'KCinflamm_late': 'KCinflamm_late',
 'KCinflamm_final': 'KCinflamm_final',
 'KCinflamm_int': 'KCinflamm_int',
 'KCinflamm_basal': 'KCinflamm_basal',
 'cDC2': 'cDC2',
 'LC': 'LC',
 'T': 'T',
 'Mast cell': 'Mast cell',
 'Melanoma': 'Melanoma',
 'F6: Myofibroblast inflammatory': 'Cancer-associated fibroblast',
 'F1: Superficial': 'Fibroblast',
 'Mac': 'Mac',
 'Nonspecific': 'Nonspecific',
 'Plasma cell': 'Plasma cell',
 'Pericyte': 'Pericyte',
 'cDC1': 'cDC1',
 'LE': 'LE',
 'F6: Myofibroblast': 'Cancer-associated fibroblast',
 'VE': 'VE',
 'MigDC': 'MigDC'}
adata.obs["key_celltype_new"]=adata.obs[key_celltype].map(RENAME)

In [ ]:
ORDER = ['Epidermis', 'Blood vessel', 'Melanoma1', 'Melanoma2',
         'Plasma cell hub', 'T_hub', 'Mac_hub', 'Stroma']

df = adata.obs.groupby(["spatial_niche", "key_celltype_new"]).size().unstack(fill_value=0)

df_norm = df.div(df.sum(axis=1), axis=0)

df_norm = df_norm.loc[:, df_norm.mean() >= 0.002]

df_norm = df_norm.reindex(ORDER, axis=0).dropna(how="all")

color_list = [colors.get(cat, "#D3D3D3") for cat in df_norm.columns]

fig, ax = plt.subplots(figsize=(9, 5))
df_norm.plot(kind="bar", stacked=True, color=color_list,
             edgecolor="black", ax=ax, linewidth=0.3)

ax.grid(False)

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

ax.set_title("")

plt.xlabel(" ")
plt.ylabel("Proportion")

handles, labels = ax.get_legend_handles_labels()
ax.legend(handles[::-1], labels[::-1], title="", bbox_to_anchor=(1.05, 1),
          loc="upper left", frameon=False)

plt.xticks(rotation=90)

plt.tight_layout()
fig.savefig("figures/spatial_composition_barplot.pdf", bbox_inches='tight')

plt.show()

In [ ]:
CATEGORY = "spatial_niche"

In [ ]:
sc.settings.set_figure_params(dpi=100, facecolor="white", frameon=False, figsize=(12, 12))

sq.pl.spatial_scatter(
        adata,
        library_id="spatial",
        shape=None,
        color=CATEGORY,
        size=10,
        title='',
        edgecolor="black",
        linewidth=0.1,
    save="spatial_umap_byspace.pdf"
    )
sq.pl.spatial_scatter(
        adata,
        library_id="spatial",
        shape=None,
        color=CATEGORY,
        size=20,
        title='',
        edgecolor="black",
        linewidth=0.1,
    )

# t cells

In [ ]:
adata_i = adata[adata.obs[key_celltype]=="T"]
adata_i.obs[CATEGORY].value_counts()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# Count the number of cells for each cell type
celltype_counts = adata_i.obs[key_celltype].value_counts()

# Filter out cell types with counts < 10
celltype_counts = celltype_counts[celltype_counts >= 50]

# Create the bar plot
fig, ax = plt.subplots(figsize=(4, 4))  # Adjust size for minimalistic style
celltype_counts.plot(
    kind="bar", 
    color="skyblue", 
    edgecolor="black", 
    ax=ax
)

# Minimalistic styling (no title, no grid)
ax.set_xlabel("", fontsize=12)
ax.set_ylabel("Cell Counts", fontsize=12)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.spines["left"].set_visible(False)
ax.tick_params(axis="x", labelrotation=90, labelsize=10)
ax.tick_params(axis="y", labelsize=10)

# Ensure grid is completely off
ax.grid(False)

# Show the plot
plt.tight_layout()
plt.show()

In [ ]:
{x:x for x in adata.obs[CATEGORY].unique() }

In [ ]:
adata_i.obs[key_celltype].value_counts()

In [ ]:
ADATA=adata_i
sc.tl.rank_genes_groups(ADATA, CATEGORY, method='t-test', key_added="de_leiden");
df2 = pd.DataFrame(ADATA.uns['de_leiden']['names'])
df2.head(10)

In [ ]:
select_population = list(df2.columns)[3
                                     ]
print(select_population)

genes0 = df2[select_population][:50]
genes1 = df2[select_population][50:100]
genes2 = df2[select_population][100:150]
genes3 = df2[select_population][150:200]
genes4 = df2[select_population][200:250]
genes5 = df2[select_population][250:300]
genes6 = df2[select_population][300:350]
genes7 = df2[select_population][350:400]
genes8 = df2[select_population][400:450]
 
# genes14 = df2[select_population][700:750]
# genes15 = df2[select_population][750:800]
# genes16 = df2[select_population][800:850]
# genes17 = df2[select_population][850:900]
# genes18 = df2[select_population][900:950]
# genes19 = df2[select_population][950:1000]
# genes20 = df2[select_population][1000:1050]
# genes21 = df2[select_population][1050:1100]
# genes22 = df2[select_population][1100:1150]
# genes23 = df2[select_population][1150:1200]
# genes24 = df2[select_population][1200:1250]
# genes25 = df2[select_population][1250:1300]
# genes26 = df2[select_population][1300:1350]
# genes27 = df2[select_population][1350:1400]

# # Define the desired order for the CATEGORY
# category_order = ['Lesional Baseline', 'Day 3', 'Day 14', 'Week 12', 'Non-lesional Baseline']

# # Ensure the CATEGORY column in adata has the desired order
# adata_i.obs[CATEGORY] = pd.Categorical(adata_i.obs[CATEGORY], categories=category_order, ordered=True)

# # Now, generate each dot plot with the specified order applied


sc.pl.dotplot(
    ADATA,
    genes0,
    groupby=CATEGORY,
    standard_scale="var",
    dendrogram=False,
)

sc.pl.dotplot(
    ADATA,
    genes1,
    groupby=CATEGORY,
    standard_scale="var",
    dendrogram=False,
)

 
sc.pl.dotplot(
    adata,
    genes0,
    groupby=key_celltype,
    standard_scale="var",
    dendrogram=False,
)

sc.pl.dotplot(
    adata,
    genes1,
    groupby=key_celltype,
    standard_scale="var",
    dendrogram=False,
)

In [ ]:
# ALL_T = {'Conventional': ['CD3D', "CD4", "CD8A"],
#               'Treg': ['FOXP3', 'TIGIT', 'CTLA4', ],
#          "Activated_Treg": ["LRRC32", "IL1R1","IL1R2",'TRAF3',  "ITGAV",
#                             #'CMSS1', 'LRRC32',
#                             'F5',# "TOX"
#                            'ZNF331', 'JMY', 'ELL2','NR4A3','NR4A1','BICDL1',

#                            ],
#               'TR1': ['EOMES', 'IL10', 'LAG3', 'HAVCR2', "PDCD1", 'FOXB1'],
#  'Naive/Tcm': ['SELL', 'CCR7', 'S1PR1', 'TCF7', "PAK2"],
#  'Th': ['CD40LG', "MCAM", "CCR6", "BACH2"],
#  'CD8A+ cytotoxic T cells': ['CD8A', 'GZMK', 'IFNG', 'TNFSF9',"CXCR3",# "MCOLN1"
#                             ],
#          "Cytotoxic": [ "NKG7","CCL5","GZMA",  ],
#          "Tissue-residency\n markers": ["ITGAE",  'ZNF683', "ENTPD1",  "RBPJ"],
# 'IL22': ['IL22', 'IL13', 'PDLIM4', #'KRT7',
#          "NBAS",  'CCL1', "CCL17", "AREG", "CCR8", "CCR10"],
#  'T_17': [ 'IL17A', 'IL17F', 'CXCL13', 'IL26', "IL21", 'CCL20', 'CTSH', "IL23R","ITGA1", 
#          "CCR6","RORC", 'TNFRSF8', "ADAM12", "IL1R1", "IL12RB2"],
#          #"Memory": ["CD69",],
#               'Gamma-delta': ["FXYD2", "TRGC2", 'TRDV1','TRGV4',  "EMP1",
#                              "NSG1", #"LINC02446","CD9", 
#                               "MPZL2", "KLRC2"], #'TRGC2', 
#              "Innate": ["KLRB1", "KIT", "KLRC1", "KLRC2", 'KLRC3', "TYROBP", "FCER1G",],
               
#                "NK": [ "TBX21",#
#                       "NCR1",#'NMUR1', "NMU",
#                       "B3GAT1", 
#                       "PTGDS",
#                       "CX3CR1", # 
#                       "CCL4L2", #
#                     #
#                       "PRSS23", "CD160", #
#                       "KLRF1", "KLRG1","S100B",
                             
#                       #"CD160", "PLEK", "NMUR1", "IL12RB1", "FGFBP2", "FCGR3A", "GZMH","AKR1C3","FGR", "CD38", 
#                      # "LAIR2", "SPON2", "S1PR5","FCRL6","PRF1", 
#                               ],
#                       "NK+ILC1": ["KLRD1","NCAM1", "PRF1"  #"IL15",
#                                  ],
#    'ILC1_NK': [ "IRF8",# 'GZMK', "IGFBP4",  "TCF7"
#                #"IL18", 
#                "ADGRG3", #"CXCR3",
#               ],
#                "ILC1/3": [ "XCL1", "XCL2", "CSF2", "KRT86" ],

#                "ILC3": ["ID3", #"ZNF683",
#                         "ZBTB46", "TNFSF4", "SPINK2", "RAMP1", "MB", "KLRF2", "TMPRSS11E", #"CAMK1", "PECAM1"
#                        ], #'TNF', "CCR8", "CD9"],

#                 "ILC2+3": ["IL9R", "TNFSF11"],
#  'ILC2': ['GATA3',  "PTGDR2", "TNFRSF25",# "BCL11B", "MAF", 
#           #"CALCRL", "HPGDS" ,  "S1PR1",
#          ],
#       'ILC2_inflammatory': [ "CRLF2", "IL17RB", "IL1RL1" , #"IL4", "IL13",'TNFRSF9',
#                             "IL18R1", "PPARG",
#                             "PTGS2", #"NBAS",# "PDLIM5", "MCAM", 
#                             "PLA2G4A", "IL4", "IL31",
#                            "ICOS", "NRROS"
#                            ],
#          "Cycling": ['UBE2C', 'MKI67', "TOP2A",# "BIRC5",
#                                 #  "MYBL2", "TPX2"
#                                   ], 
#                }
# def remove_markers(LIST):
#     try: 
#         LIST = {key: [gene for gene in genes if gene in adata.var_names] 
#                            for key, genes in LIST.items()}
#     except: 
#         LIST =[gene for gene in LIST if gene in adata.var_names]
#     return LIST



# sc.pl.dotplot(adata_i, 
#               remove_markers(ALL_T),
#               groupby=CATEGORY,
#               dendrogram=False, 
#                 standard_scale="var")


# # sc.pl.dotplot(adata_5k_i, 
# #               remove_markers(ALL_T),
# #               groupby=CATEGORY,
# #               dendrogram=False, 
# #                 standard_scale="var",
# #              dot_max=0.3,)

In [ ]:
adata_i

In [ ]:
# import squidpy as sq
# colors = {
#     'Epidermis mid': '#839edd',  # blue
#     'Epidermis late': '#b1dae6',  # light blue 
#     'Epidermis basal': '#505aa1',  # dark blue
#     'Superficial dermis': '#FFFF00',  # yellow
#     'Superficial dermis / inflammatory memory': "#f6d17a", #"#f6d178", #'#FFA500',  # orange
#     'Perivascular_T-rich': "#dcb0f2", #NICE PRUPLE, # lighter prupkle = "#E5D4F6", # #'#a3dbe5',  # brown
#     'Interstial stroma1': "#aec8e8", # "#FF6600", #pink#"#ffbdc8",# '#FFD700',  # dark yellow
#     'Perivascular':  "#845DAE", #  '#fedbe7' PINKSIH,  #'#f8daeb',  # darkish red
#     'Sweat gland channel': '#40E0D0',  # grey
#     'Small blood vessel': "#d73435", #'#fe78bb',  # bright red
#     'Interstial stroma2': "#5A82B8", #pinkish "#dc9cab",# "#ff68b3",#'#B8860B',  # very dark yellow
#     'Sweat gland': '#008080',  # dark grey
#     'Muscle': "#f371af",  # very dark red
#     'Adipocyte+vessels': "#B8860B", #'#FF4500',  # very dark orange
#     'Epidermis mid inflammatory': '#f4e9ef',  # pink
#     'Larger blood vessel': "#660000",#"#8B0000", #'#FF6347',  # coral red
#     'Perineural': '#0A0A0A',  # almost black
#     'KC_HF1_outer':  "#94cb72", #'#008000',  # green
#     'Sebocyte_immunecell': "#ff6145",#'#654321',  # dark brown
#     'Sebocyte': '#e28743',  # brown
#     'Plasma+pDC': '#808080',  # bright turquoise
#     'Epidermis basal/mid': '#4682B4',  # darkish blue
#     #'Sweat gland channel': '#000000',  # black
#     #'KC_immunecell': '#FF1493',  # dark pink
#     'Perifollicular_VE': '#006400',  # dark green
#     'KC_HF2_basal': '#7CFC00',  # bright green
#     'KC_HF4_medulla': '#00FF00',  # very bright green
#     'KC_HF3_inner': "#abe8bd", #'#228B22',  # darkish green
#     'KC_immune': '#FFB6C1',  # light pink
#      'KCinflamm_late': '#c8cada',  # very dark blue
#     'Artery_endothelium': '#fe78bd'  # bright red
# }
# adata_5k.obs['niche_name'] =adata_5k.obs['niche_name'] .astype('category')
# adata_5k.uns['niche_name_colors'] = [colors.get(cat, '#D3D3D3')  # Default to light grey if not found
#                                      for cat in adata_5k.obs['niche_name'].cat.categories]

# timepoints = [ 'Lesional Baseline',  ]

# # Identify unique donors
# donors = ["BK18", #"BK23"
#          ]
# sc.settings.set_figure_params(dpi=100, facecolor="white", frameon=False, figsize=(18,18))

# # Generate a spatial plot for each donor and timepoint combination
# for row, donor in enumerate(donors):
#     for col, timepoint in enumerate(timepoints):
#         donor_timepoint_data = adata_5k[
#             (adata_5k.obs["Sanger patient ID"] == donor) & (adata_5k.obs["Timepoint"] == timepoint)
#         ]
        
   
#         sq.pl.spatial_scatter(
#             donor_timepoint_data,
#             library_id="spatial",
#             shape=None,
#             color="niche_name",
#             size=10,
#             vmax=1,
#             #ax=ax,
#             legend_loc="on data"  # Disable the legend for each subplot
#         ) 
#         sq.pl.spatial_scatter(
#             donor_timepoint_data,
#             library_id="spatial",
#             shape=None,
#             color="niche_name",
#             size=5,
#             vmax=1,
#             #ax=ax,
#             #legend_loc=None # Disable the legend for each subplot
#         )

In [ ]:
# in this plot, how can i colour:
#        'Dermis': '#8C6A3B',
#     'Superficial': '#F87A7B',
        
#         # Define your color mapping
# COLOR = {
#     'Basal':'#f4e9ef',# '#839edd',
#     'Mid':  '#505aa1',
#     'Late': '#007FFF'
# }

In [ ]:
# colors={'Adipocyte': '#B8860B',
#  'F1: Superficial': '#FFFFE4',
#  'F1: Regenerative': '#FFFFE4',

# 'F2/3: Stroma_PPARG+': '#78b5d7',
#  'F2: Universal': '#d0e1f2',
#  'F3: FRC-like': '#fbd4d7',
#  'F4: DS_DPEP1+': '#d3eec9',
#  'F4: TNN+COCH+': '#80ca80',
#  'F5: NGFR+': '#788bd2',
#  'F5: RAMP1+': '#9e99c9',
#  'F6: Inflammatory myofibroblast': '#00ffff',
#  'KC1-2': '#505aa1',
#  'KC2/3_cycling': '#007FFF',
#  'KC3': '#839edd',
#  'KC4': '#b1dae6',
#  'KC5': '#c8cada',
#  'KC_HF: Basal': '#006400',
#          'KC_HF: m': '#abe8bd',

#  'KC_HF: IRS+HS': '#abe8bd',
#  'KC_HF: ORS/CL': '#94cb72',
#         "KC_HF: IRS+HS_medulla": "#94cb72",
#  'KC_SC: LGR6+ACTA2+': "#008080",#'#004444',
#  'KCinflamm_basal/int': '#f4e9ef',
#  'KCinflamm_late': '#D49BB1',
#  'LC': '#63D7F0',
# # 'LC_CCR7+': '#5F3D7D',
#  'LC_SLC18A2+': '#3bc1d9',
#  'LE': '#FFFF00',
#  'Mac': '#845DAE',
#  'Mac2_CCL14hi': '#4F2F6D',
#  'Mast cell': '#FF1493',
#  'Melanocyte': '#6f3a3a',
#  'MigDC': '#00FF00',
#  'Smooth muscle': '#f371af',
#  'Nonspecific': '#D3D3D3',
#  'Pericyte1_CCL19+': '#F7A3C3',
#  'Pericyte2_CASQ2+': '#D04A8A',
#  'Plasma cell': '#ff5e00',
#  'KC_Sebocyte_basal': '#e28743',
#  'KC_Sebocyte_inner': '#ffd1a3',
#  'Sweat gland': '#00CCCC',
#  'Sweat gland channel': '#2DA8A0',
#  'Sweat gland channel_inner': "#FFE5B4",#'#D1F9F6',
# # 'Sweat gland channel outer': 'Sweat gland channel outer',
#  'Sweat gland channel_outer': "#B3FFF0",#'#40E0D0',
#    'T': '#F4D1A1',
#     'T_Prolif': '#D4B082',
#     'Tc': '#8C6A3B',
#     'Tc_IL13': '#F87A7B',
#     'Tnaive/Tcm': '#C6A476',
#     'Treg': '#9E7A55',
#     'Treg_LRRC32': "#9E5E3A",#'#7E5F43',
#  'VE2': '#9f1a1a',
#  'VE1_ADAMTS6_Art': '#660000',
#  'VE3_SELPhi': '#d73435',
#  'cDC1': '#9B70C1',
#  'cDC2': '#6F478C',
#   'cDC2: MMP12+': '#7D56A3',
#  'mSchwann': '#3A3A30',
#  'nmSchwann': '#0A0A0A',
#  'pDC': '#D85B8C',
        
        
        
# ### scrna only
#         'AXL+SIGLEC6+ DC': "#9b4ef5",
# 'Bcell': "#e14d00",
# 'Cartilage': "#404040", 
# 'F4: DP_HHIP+': "#26a83f",
# 'F6: Inflammatory myofibroblast': "#00ffff",
# 'F_Fascia': "#000000",
# 'ILC1_3': "#FFFF00",
# 'ILC1_NK': "#F4D03F",
# 'ILC2': "#F1C40F",
# 'ILC2_inflammatory': "#C79A00",
# 'KC1': "#3a4e7a",
# 'KC2': "#505aa1",
# 'KC_HF: Basal_LGR5+': "#00b300",
# 'KC_HF: Basal_NPNT+': "#006400",
# 'KCinflamm_basal': "#f9f3fb",
# 'KCinflamm_cycling':"#e0c5d2",
# 'KCinflamm_int': "#f5d3e7",
# 'LC_CCR7+': "#3bc1a4",
# 'Mac1': "#6A3F9B",
# 'MacTREM2_CX3CR1+': "#9D1A80",
# 'Merkel cell': "#2f2f2f",
# 'MoDC': "#7F00A2",
# "MoDC/cDC2: MMP12+": "#7F00A2",
# "MoDC/cDC2": "#7F00A2",
        
# 'Mono': "#D8A7FF",
# 'Mono CD16+': "#E1C6FF",
# 'NK': "#FFEB3B",
# 'Neutrophil': "#4D3F8C",
# 'Satellite muscle': "#F387C7",
# 'Skeletal muscle': "#F14D8E",
# 'Tc_IFNGhi': "#F5A600",
# 'Tc_IL17': "#B84A3D",#"#A75C3E",
# 'Tc_ZNF683+/γδ': "#D4B082",
# 'Th': "#F4D1A1",
# 'Tr1': "#5F452F", 
# 'cDC2: IL1B+': "#B78FE1",
       
#        }
# import pickle
# file_path = '/nfs/team298/ls34/color_for_adult_skin.pkl'

# # Save the dictionary to the file
# with open(file_path, 'wb') as file:
#     pickle.dump(colors, file)
# adata_5k.obs['lvl4_annotation'] =adata_5k.obs['lvl4_annotation'] .astype('category')
# adata_5k.uns['lvl4_annotation_colors'] = [colors.get(cat, '#D3D3D3')  # Default to light grey if not found
#                                      for cat in adata_5k.obs['lvl4_annotation'].cat.categories]

# timepoints = [ 'Non-lesional Baseline',  ]

# # Identify unique donors
# donors = ["BK18", #"BK23", "BK24", "BK30"
#          ]
# sc.settings.set_figure_params(dpi=300, facecolor="white", frameon=False, figsize=(18,18))
# import squidpy as sq

# # Generate a spatial plot for each donor and timepoint combination
# for row, donor in enumerate(donors):
#     for col, timepoint in enumerate(timepoints):
#         donor_timepoint_data = adata_5k[
#             (adata_5k.obs["Sanger patient ID"] == donor) & (adata_5k.obs["Timepoint"] == timepoint)
#         ]
        
   
# #         sq.pl.spatial_scatter(
# #             donor_timepoint_data,
# #             library_id="spatial",
# #             shape=None,
# #             color="veryfine_celltypes",
# #             size=10,
# #             vmax=1,
# #             #ax=ax,
# #             legend_loc="on data"  # Disable the legend for each subplot
# #         ) 
#         sq.pl.spatial_scatter(
#             donor_timepoint_data,
#             library_id="spatial",
#             shape=None,
#             color="lvl4_annotation",
#             size=50,
#             vmax=1,
#            # legend_loc="on data",
#                 edgecolor='black',
#     linewidth=0.03,
#             #ax=ax,
            
#            legend_loc=None # Disable the legend for each subplot
#         ) 
# sc.settings.set_figure_params(dpi=100, facecolor="white", frameon=False, figsize=(18,18))

# sc.pl.umap(
#     adata_5k,
#     color=[
#         "lvl4_annotation"
#     ],
#     legend_loc="on data",
#     s=10, legend_fontsize=8,legend_fontoutline=2,
 

# )

In [ ]:
import pandas as pd
# #adata.uns['log1p']['base'] = None
CATEGORY = key_celltype
#ADATA = adata_i

sc.tl.rank_genes_groups(adata, CATEGORY, method='t-test', key_added="de_leiden");
df2 = pd.DataFrame(adata.uns['de_leiden']['names'])
for i,x in enumerate(df2.columns):
     print(i,":",x)
T_GENES = list(df2["T"].values[:200])
MELANOMA_GENES = list(df2["Melanoma"].values[:400])

In [ ]:
3

In [ ]:
select_population = list(df2.columns)[-2
                                     ]
print(select_population)
#GENE_LIST_DEG_ALL =  df2[select_population][:500]
#GENE_LIST_DEG_ALL = [x for x in GENE_LIST_DEG_ALL if x not in MELANOMA_GENES]
genes0 = GENE_LIST_DEG_ALL[:100]
genes1 = GENE_LIST_DEG_ALL[50:100]
genes2 = GENE_LIST_DEG_ALL[100:150]
genes3 = GENE_LIST_DEG_ALL[150:200]
genes4 = GENE_LIST_DEG_ALL[200:250]
genes5 = GENE_LIST_DEG_ALL[250:300]
genes6 = GENE_LIST_DEG_ALL[300:350]
genes7 = GENE_LIST_DEG_ALL[350:400]
genes8 = GENE_LIST_DEG_ALL[400:450]
genes9 = GENE_LIST_DEG_ALL[450:500]

sc.pl.matrixplot(
    adata,
    genes0,
    groupby=CATEGORY,
    standard_scale="var",
    dendrogram=False,
    cmap="Reds"
)
# ) 
# sc.pl.dotplot(
#     adata,
#     genes1,
#     groupby=CATEGORY,
#     standard_scale="var",
#     dendrogram=False,
# ) 
# sc.pl.dotplot(
#     adata,
#     genes2,
#     groupby=CATEGORY,
    
#     standard_scale="var",
#     dendrogram=False,
# ) 
# # sc.pl.dotplot(
#     adata_subset,
#     genes3,
#     groupby="celltype_annotation4",
#     standard_scale="var",
#     dendrogram=False,
 )

In [ ]:
list(df2.columns)

In [ ]:
select_population = list(df2.columns)[-1
                                     ]
print(select_population)
GENE_LIST_DEG_ALL =  df2[select_population][:500]
#GENE_LIST_DEG_ALL = [x for x in GENE_LIST_DEG_ALL if x not in MELANOMA_GENES]
genes0 = GENE_LIST_DEG_ALL[:100]
genes1 = GENE_LIST_DEG_ALL[50:100]
genes2 = GENE_LIST_DEG_ALL[100:150]
genes3 = GENE_LIST_DEG_ALL[150:200]
genes4 = GENE_LIST_DEG_ALL[200:250]
genes5 = GENE_LIST_DEG_ALL[250:300]
genes6 = GENE_LIST_DEG_ALL[300:350]
genes7 = GENE_LIST_DEG_ALL[350:400]
genes8 = GENE_LIST_DEG_ALL[400:450]
genes9 = GENE_LIST_DEG_ALL[450:500]

sc.pl.matrixplot(
    adata,
    genes0,
    groupby=CATEGORY,
    standard_scale="var",
    dendrogram=False,
    cmap="Reds"
)
# ) 
# sc.pl.dotplot(
#     adata,
#     genes1,
#     groupby=CATEGORY,
#     standard_scale="var",
#     dendrogram=False,
# ) 
# sc.pl.dotplot(
#     adata,
#     genes2,
#     groupby=CATEGORY,
    
#     standard_scale="var",
#     dendrogram=False,
# ) 
# # sc.pl.dotplot(
#     adata_subset,
#     genes3,
#     groupby="celltype_annotation4",
#     standard_scale="var",
#     dendrogram=False,
# )

# T cell

In [ ]:
adata_i = adata[adata.obs[key_celltype].str.startswith("T")]
adata_i

sc.pp.neighbors(adata_i, use_rep = 'X_pca', 
                metric = "euclidean", n_neighbors=20)#key_added=neighbor_id)


sc.tl.umap(adata_i, min_dist=0.1) #neighbor_key=)


sc.pl.umap(adata_i,  
           color=[ "niche_name", key_celltype],
           s=200,legend_loc="on data",
           legend_fontsize=8)

RES=0.5
sc.tl.leiden(adata_i, #restrict_to=(CATEGORY,subset_cluster), 
             resolution=RES, random_state=1, key_added=f'leiden_res{RES}') #neighbors_key='neighbor_30')

sc.settings.set_figure_params(dpi=100, facecolor="white", frameon=False, figsize=(12, 12))
sc.pl.umap(adata_i,  
           color=[ "niche_name", f"leiden_res{RES}"],
           s=200,legend_loc="on data",
           legend_fontsize=8)

In [ ]:
adata_i.write('/nfs/team361/ls34/inflow/adata_tcells_mm.h5ad')

In [ ]:

import pandas as pd
# #adata.uns['log1p']['base'] = None
CATEGORY = f"leiden_res{RES}"
#ADATA = adata_i

sc.tl.rank_genes_groups(adata_i, CATEGORY, method='t-test', key_added="de_leiden");
df2 = pd.DataFrame(adata_i.uns['de_leiden']['names'])
for i,x in enumerate(df2.columns):
     print(i,":",x)
        
select_population = list(df2.columns)[1
                                     ]
print(select_population)
GENE_LIST_DEG_ALL =  df2[select_population][:500]
GENE_LIST_DEG_ALL = [x for x in GENE_LIST_DEG_ALL if x not in MELANOMA_GENES]
genes0 = GENE_LIST_DEG_ALL[:50]
genes1 = GENE_LIST_DEG_ALL[50:100]
genes2 = GENE_LIST_DEG_ALL[100:150]
genes3 = GENE_LIST_DEG_ALL[150:200]
genes4 = GENE_LIST_DEG_ALL[200:250]
genes5 = GENE_LIST_DEG_ALL[250:300]
genes6 = GENE_LIST_DEG_ALL[300:350]
genes7 = GENE_LIST_DEG_ALL[350:400]
genes8 = GENE_LIST_DEG_ALL[400:450]
genes9 = GENE_LIST_DEG_ALL[450:500]

sc.pl.dotplot(
    adata_i,
    genes0,
    groupby=CATEGORY,
    #standard_scale="var",
    dendrogram=False,
) 
sc.pl.dotplot(
    adata_i,
    genes1,
    groupby=CATEGORY,
    standard_scale="var",
    dendrogram=False,
) 
sc.pl.dotplot(
    adata_i,
    genes2,
    groupby=CATEGORY,
    
    standard_scale="var",
    dendrogram=False,
) 
# sc.pl.dotplot(
#     adata_subset,
#     genes3,
#     groupby="celltype_annotation4",
#     standard_scale="var",
#     dendrogram=False,
# )

In [ ]:

ALL_T = {'Conventional': ['CD3D', "CD4", "CD8A"],
              'Treg': ['FOXP3', 'TIGIT', 'CTLA4', ],
         "Activated_Treg": ["LRRC32", "IL1R1","IL1R2",'TRAF3', 
                            #'CMSS1', 'LRRC32',
                            'F5',# "TOX"
                           'ZNF331', 'JMY', 'ELL2','NR4A3','NR4A1','BICDL1',

                           ],
              'TR1': ['EOMES', 'IL10', 'LAG3', 'HAVCR2', "PDCD1", 'FOXB1'],
 'Naive/Tcm': ['SELL', 'CCR7', 'S1PR1', 'TCF7', "PAK2"],
 'Th': ['CD40LG', "MCAM", "CCR6", "BACH2"],
 'CD8A+ cytotoxic T cells': ['CD8A', 'GZMK', 'IFNG', 'TNFSF9',"CXCR3",# "MCOLN1"
                            ],
         "Cytotoxic": [ "NKG7","CCL5","GZMA",  ],
         "Tissue-residency\n markers": ["ITGAE",  'ZNF683', "ENTPD1",  "RBPJ"],
'IL22': ['IL22', 'IL13', 'PDLIM4', #'KRT7',
         "NBAS",  'CCL1', "CCL17", "AREG"],
 'T_17': [ 'IL17A', 'IL17F', 'CXCL13', 'IL26', 'CCL20', 'CTSH', "IL23R","ITGA1", 
         "CCR6","RORC", 'TNFRSF8', "ADAM12"],
         #"Memory": ["CD69",],
              'Gamma-delta': ["FXYD2", "TRGC2", 'TRDV1','TRGV4',  "EMP1",
                             "NSG1", #"LINC02446","CD9", 
                              "MPZL2", "KLRC2"], #'TRGC2', 
             "Innate": ["KLRB1", "KIT", "KLRC1", "KLRC2", 'KLRC3', "TYROBP", "FCER1G",],
               
               "NK": [ "TBX21",#
                      "NCR1",#'NMUR1', "NMU",
                      "B3GAT1", 
                      "PTGDS",
                      "CX3CR1", # 
                      "CCL4L2", #
                    #
                      "PRSS23", "CD160", #
                      "KLRF1", "KLRG1","S100B",
                             
                      #"CD160", "PLEK", "NMUR1", "IL12RB1", "FGFBP2", "FCGR3A", "GZMH","AKR1C3","FGR", "CD38", 
                     # "LAIR2", "SPON2", "S1PR5","FCRL6","PRF1", 
                              ],
                      "NK+ILC1": ["KLRD1","NCAM1", "PRF1"  #"IL15",
                                 ],
   'ILC1_NK': [ "IL12RB2", "IRF8",# 'GZMK', "IGFBP4",  "TCF7"
               #"IL18", 
               "ADGRG3", #"CXCR3",
              ],
               "ILC1/3": [ "XCL1", "XCL2", "CSF2", "KRT86" ],

               "ILC3": ["ID3", #"ZNF683",
                        "ZBTB46", "TNFSF4", "SPINK2", "RAMP1", "MB", "KLRF2", "TMPRSS11E", #"CAMK1", "PECAM1"
                       ], #'TNF', "CCR8", "CD9"],

                "ILC2+3": ["IL9R", "TNFSF11"],
 'ILC2': ['GATA3',  "PTGDR2", "TNFRSF25",# "BCL11B", "MAF", 
          #"CALCRL", "HPGDS" ,  "S1PR1",
         ],
      'ILC2_inflammatory': [ "CRLF2", "IL17RB", "IL1RL1" , #"IL4", "IL13",'TNFRSF9',
                            "IL18R1", "PPARG",
                            "PTGS2", #"NBAS",# "PDLIM5", "MCAM", 
                            "PLA2G4A", "IL4", "IL31"],
         "Cycling": ['UBE2C', 'MKI67', "TOP2A",# "BIRC5",
                                #  "MYBL2", "TPX2"
                                  ], 
     
               }



sc.pl.dotplot(adata_i, 
              remove_markers(ALL_T),
              groupby=f'leiden_res{RES}',
              dendrogram=False, 
                standard_scale="var",
             dot_max=0.3,)


sc.pl.dotplot(adata_i, 
              remove_markers(ALL_T),
              groupby=f'spatial_niche',
              dendrogram=False, 
                standard_scale="var",
             dot_max=0.3,)

In [ ]:
import pandas as pd
# #adata.uns['log1p']['base'] = None
CATEGORY = f"spatial_niche"
#ADATA = adata_i

sc.tl.rank_genes_groups(adata_i, CATEGORY, method='t-test', key_added="de_leiden");
df2 = pd.DataFrame(adata_i.uns['de_leiden']['names'])
for i,x in enumerate(df2.columns):
     print(i,":",x)
        
        
select_population = list(df2.columns)[-1
                                     ]
print(select_population)
GENE_LIST_DEG_ALL =  df2[select_population][:500]
GENE_LIST_DEG_ALL = [x for x in GENE_LIST_DEG_ALL if x not in MELANOMA_GENES]
genes0 = GENE_LIST_DEG_ALL[:50]
genes1 = GENE_LIST_DEG_ALL[50:100]
genes2 = GENE_LIST_DEG_ALL[100:150]
genes3 = GENE_LIST_DEG_ALL[150:200]
genes4 = GENE_LIST_DEG_ALL[200:250]
genes5 = GENE_LIST_DEG_ALL[250:300]
genes6 = GENE_LIST_DEG_ALL[300:350]
genes7 = GENE_LIST_DEG_ALL[350:400]
genes8 = GENE_LIST_DEG_ALL[400:450]
genes9 = GENE_LIST_DEG_ALL[450:500]

sc.pl.dotplot(
    adata_i,
    genes0,
    groupby=CATEGORY,
    #standard_scale="var",
    dendrogram=False,
) 
sc.pl.dotplot(
    adata_i,
    genes1,
    groupby=CATEGORY,
    standard_scale="var",
    dendrogram=False,
) 
sc.pl.dotplot(
    adata_i,
    genes2,
    groupby=CATEGORY,
    
    standard_scale="var",
    dendrogram=False,
) 
# sc.pl.dotplot(
#     adata_subset,
#     genes3,
#     groupby="celltype_annotation4",
#     standard_scale="var",
#     dendrogram=False,
# )

In [ ]:
sc.pl.umap(adata_i,  
           color=[ "CD4","ZNF683"],
           s=200,legend_loc="on data",
           legend_fontsize=8, vmax=20)

In [ ]:

sc.pl.dotplot(
    adata,
    ["CXCL12", "CCL19"],
    groupby="spatial_niche",
    standard_scale="var",
    dendrogram=False,
)

In [ ]:
import pandas as pd
# #adata.uns['log1p']['base'] = None
CATEGORY = f"spatial_niche"
#ADATA = adata_i
adata_ii=adata_i[adata_i.obs["spatial_niche"].isin(["T_hub", "Myofibroblast_T", "Melanoma2", "Melanoma1"])]
sc.tl.rank_genes_groups(adata_ii, CATEGORY, method='t-test', key_added="de_leiden");
df2 = pd.DataFrame(adata_ii.uns['de_leiden']['names'])
for i,x in enumerate(df2.columns):
     print(i,":",x)

In [ ]:

        
select_population = list(df2.columns)[0
                                     ]
print(select_population)
GENE_LIST_DEG_ALL =  df2[select_population][:500]
GENE_LIST_DEG_ALL = [x for x in GENE_LIST_DEG_ALL if x not in MELANOMA_GENES]
genes0 = GENE_LIST_DEG_ALL[:50]
genes1 = GENE_LIST_DEG_ALL[50:100]
genes2 = GENE_LIST_DEG_ALL[100:150]
genes3 = GENE_LIST_DEG_ALL[150:200]
genes4 = GENE_LIST_DEG_ALL[200:250]
genes5 = GENE_LIST_DEG_ALL[250:300]
genes6 = GENE_LIST_DEG_ALL[300:350]
genes7 = GENE_LIST_DEG_ALL[350:400]
genes8 = GENE_LIST_DEG_ALL[400:450]
genes9 = GENE_LIST_DEG_ALL[450:500]

sc.pl.dotplot(
    adata_ii,
    genes0,
    groupby=CATEGORY,
    standard_scale="var",
    dendrogram=False,
) 
sc.pl.dotplot(
    adata_ii,
    genes1,
    groupby=CATEGORY,
    standard_scale="var",
    dendrogram=False,
) 
sc.pl.dotplot(
    adata_ii,
    genes2,
    groupby=CATEGORY,
    
    standard_scale="var",
    dendrogram=False,
) 
# sc.pl.dotplot(
#     adata_subset,
#     genes3,
#     groupby="celltype_annotation4",
#     standard_scale="var",
#     dendrogram=False,
# )

In [ ]:
sc.pl.dotplot(
    adata,
    ["SIRPA", "SNX10", "DMKN", "LGALSL"],
    groupby=key_celltype,
    
    standard_scale="var",
    dendrogram=False,
)

In [ ]:
MELANOMA_SET=['CXCL12', 'CCL19',]
sq.pl.spatial_scatter(
        adata,
        library_id="spatial",
        shape=None,
        color=MELANOMA_SET,
        size=1,
        title='',
        vmax=20
    )

In [ ]:

# Define colors for "Melanoma" and "Other"
custom_colors = {
    "Melanoma": "#8B5A2B",  # Light brown
    "Other": "#D3D3D3"  # Light grey
}

# Assign colors to the .uns dictionary in the order they appear in the "mm" category
adata.obs["mm"] = ["Melanoma" if x == "Melanoma" else "Other" for x in adata.obs[key_celltype]]

# Ensure "mm" is a categorical variable
adata.obs["mm"] = adata.obs["mm"].astype("category")

# Store the colors in .uns
adata.uns["mm_colors"] = [custom_colors[cat] for cat in adata.obs["mm"].cat.categories]

# Plot
sq.pl.spatial_scatter(
    adata,
    library_id="spatial",
    shape=None,
    color="mm",
    size=1,
    title="",
    vmax=20,
    save="mm_cells.pdf"
)

In [ ]:

# Define colors for "Melanoma" and "Other"
custom_colors = {
    "T": "#8C6A3B",   # "#8B5A2B",  # Light brown
    "Other": "#D3D3D3"  # Light grey
}

# Assign colors to the .uns dictionary in the order they appear in the "mm" category
adata.obs["mm"] = ["T" if x == "T" else "Other" for x in adata.obs[key_celltype]]

# Ensure "mm" is a categorical variable
adata.obs["mm"] = adata.obs["mm"].astype("category")

# Store the colors in .uns
adata.uns["mm_colors"] = [custom_colors[cat] for cat in adata.obs["mm"].cat.categories]

# Plot
sq.pl.spatial_scatter(
    adata,
    library_id="spatial",
    shape=None,
    color="mm",
    size=2,
    title="",
    vmax=20,
        save="t_cells.pdf"

)

In [ ]:

import scanpy as sc
import squidpy as sq

# Define colors for "Melanoma" and "Other"
custom_colors = {
    "T_hub": "#F4D1A1",   # "#8B5A2B",  # Light brown
    "Other": "#D3D3D3"  # Light grey
}

# Assign colors to the .uns dictionary in the order they appear in the "mm" category
adata.obs["mm"] = [x if x == "T_hub" else "Other" for x in adata.obs["spatial_niche"]]

# Ensure "mm" is a categorical variable
adata.obs["mm"] = adata.obs["mm"].astype("category")

# Store the colors in .uns
adata.uns["mm_colors"] = [custom_colors[cat] for cat in adata.obs["mm"].cat.categories]

# Plot
sq.pl.spatial_scatter(
    adata,
    library_id="spatial",
    shape=None,
    color="mm",
    size=1,
    title="",
    vmax=20,
        save="thub_cells.pdf"

    #edgecolor='black',
    #linewidth=0.1
)
 
#     COLORS = {'Epidermis': '#0000FF',
#  'T_hub': '#F4D1A1',
#  'Melanoma2': '#A9A9A9', #BROWN = 5C4033
#  'Blood vessel': '#d73435',
#  'Mac_hub': '#4B0082',
#  'Melanoma1': '#000000',
#  'Myofibroblast_T': '#FFFF00',
#  'Plasma cell hub': '#4DFFFF'}

In [ ]:

import scanpy as sc
import squidpy as sq

# Define colors for "Melanoma" and "Other"
custom_colors = {
    "Stroma": "#8C6A3B",   # "#8B5A2B",  # Light brown
    "Other": "#D3D3D3"  # Light grey
}

# Assign colors to the .uns dictionary in the order they appear in the "mm" category
adata.obs["mm"] = [x if x == "Stroma" else "Other" for x in adata.obs["spatial_niche"]]

# Ensure "mm" is a categorical variable
adata.obs["mm"] = adata.obs["mm"].astype("category")

# Store the colors in .uns
adata.uns["mm_colors"] = [custom_colors[cat] for cat in adata.obs["mm"].cat.categories]

# Plot
sq.pl.spatial_scatter(
    adata,
    library_id="spatial",
    shape=None,
    color="mm",
    size=2,
    title="",
    vmax=20,
            save="stroma_cells.pdf"

)

In [ ]:
# sc.settings.set_figure_params(dpi=300, facecolor="white", frameon=False, figsize=(6,6))
# adata.obs["mm"] = [x if x =="Melanoma" else "Other" for x in adata.obs[key_celltype]] 
# sq.pl.spatial_scatter(
#         adata,
#         library_id="spatial",
#         shape=None,
#         color="mm",
#         size=1,
#         title='',
#         vmax=20,
#     cmap=[   "#C4A484",  # Light brown
#  "#D3D3D3"  # Light grey
# ]
#     )
# sc.settings.set_figure_params(dpi=300, facecolor="white", frameon=False, figsize=(16,16))

In [ ]:
def remove_markers(LIST):
    try: 
        LIST = {key: [gene for gene in genes if gene in adata.var_names] 
                           for key, genes in LIST.items()}
    except: 
        LIST =[gene for gene in LIST if gene in adata_5k.var_names]
    return LIST

In [ ]:
adata_i = adata[adata.obs[key_celltype].str.startswith("T")]
adata_i
sc.pp.neighbors(adata_i, use_rep = M_BAR_METRIC, 
                metric = "euclidean", n_neighbors=20)#key_added=neighbor_id)
sc.tl.umap(adata_i, min_dist=0.1) #neighbor_key=)


sc.pl.umap(adata_i,  
           color=[ "NICHE_NAMES", key_celltype],
           s=200,legend_loc="on data",
           legend_fontsize=8)

RES=0.1
sc.tl.leiden(adata_i, #restrict_to=(CATEGORY,subset_cluster), 
             resolution=RES, random_state=1, key_added=f'leiden_res{RES}') #neighbors_key='neighbor_30')



sc.pl.umap(adata_i,  
           color=[ key_celltype, f"leiden_res{RES}"],
           s=200,legend_loc="on data",
           legend_fontsize=8
          )
           
           
for x in adata.obs["info_id"].unique():
    adata_ii=adata_i[adata_i.obs["info_id"]==x]
    adata_iii=adata[adata.obs["info_id"]==x]

    sq.pl.spatial_scatter(
            adata_ii,
            library_id="spatial",
            shape=None,
            color=f'leiden_res{RES}',
            size=100,
            title=''
        )

    # try:
    #     adata_i.uns.pop('niche_colors')
    # except:
    #     1
    sq.pl.spatial_scatter(
            adata_iii,
            library_id="spatial",
            shape=None,
            color=f'NICHE_NAMES',
            size=10,
            title=''
        )


ALL_T = {'Conventional': ['CD3D', "CD4", "CD8A"],
              'Treg': ['FOXP3', 'TIGIT', 'CTLA4', ],
         "Activated_Treg": ["LRRC32", "IL1R1","IL1R2",'TRAF3', 
                            #'CMSS1', 'LRRC32',
                            'F5',# "TOX"
                           'ZNF331', 'JMY', 'ELL2','NR4A3','NR4A1','BICDL1',

                           ],
              'TR1': ['EOMES', 'IL10', 'LAG3', 'HAVCR2', "PDCD1", 'FOXB1'],
 'Naive/Tcm': ['SELL', 'CCR7', 'S1PR1', 'TCF7', "PAK2"],
 'Th': ['CD40LG', "MCAM", "CCR6", "BACH2"],
 'CD8A+ cytotoxic T cells': ['CD8A', 'GZMK', 'IFNG', 'TNFSF9',"CXCR3",# "MCOLN1"
                            ],
         "Cytotoxic": [ "NKG7","CCL5","GZMA",  ],
         "Tissue-residency\n markers": ["ITGAE",  'ZNF683', "ENTPD1",  "RBPJ"],
'IL22': ['IL22', 'IL13', 'PDLIM4', #'KRT7',
         "NBAS",  'CCL1', "CCL17", "AREG"],
 'T_17': [ 'IL17A', 'IL17F', 'CXCL13', 'IL26', 'CCL20', 'CTSH', "IL23R","ITGA1", 
         "CCR6","RORC", 'TNFRSF8', "ADAM12"],
         #"Memory": ["CD69",],
              'Gamma-delta': ["FXYD2", "TRGC2", 'TRDV1','TRGV4',  "EMP1",
                             "NSG1", #"LINC02446","CD9", 
                              "MPZL2", "KLRC2"], #'TRGC2', 
             "Innate": ["KLRB1", "KIT", "KLRC1", "KLRC2", 'KLRC3', "TYROBP", "FCER1G",],
               
               "NK": [ "TBX21",#
                      "NCR1",#'NMUR1', "NMU",
                      "B3GAT1", 
                      "PTGDS",
                      "CX3CR1", # 
                      "CCL4L2", #
                    #
                      "PRSS23", "CD160", #
                      "KLRF1", "KLRG1","S100B",
                             
                      #"CD160", "PLEK", "NMUR1", "IL12RB1", "FGFBP2", "FCGR3A", "GZMH","AKR1C3","FGR", "CD38", 
                     # "LAIR2", "SPON2", "S1PR5","FCRL6","PRF1", 
                              ],
                      "NK+ILC1": ["KLRD1","NCAM1", "PRF1"  #"IL15",
                                 ],
   'ILC1_NK': [ "IL12RB2", "IRF8",# 'GZMK', "IGFBP4",  "TCF7"
               #"IL18", 
               "ADGRG3", #"CXCR3",
              ],
               "ILC1/3": [ "XCL1", "XCL2", "CSF2", "KRT86" ],

               "ILC3": ["ID3", #"ZNF683",
                        "ZBTB46", "TNFSF4", "SPINK2", "RAMP1", "MB", "KLRF2", "TMPRSS11E", #"CAMK1", "PECAM1"
                       ], #'TNF', "CCR8", "CD9"],

                "ILC2+3": ["IL9R", "TNFSF11"],
 'ILC2': ['GATA3',  "PTGDR2", "TNFRSF25",# "BCL11B", "MAF", 
          #"CALCRL", "HPGDS" ,  "S1PR1",
         ],
      'ILC2_inflammatory': [ "CRLF2", "IL17RB", "IL1RL1" , #"IL4", "IL13",'TNFRSF9',
                            "IL18R1", "PPARG",
                            "PTGS2", #"NBAS",# "PDLIM5", "MCAM", 
                            "PLA2G4A", "IL4", "IL31"],
         "Cycling": ['UBE2C', 'MKI67', "TOP2A",# "BIRC5",
                                #  "MYBL2", "TPX2"
                                  ], 
     
               }



sc.pl.dotplot(adata_i, 
              remove_markers(ALL_T),
              groupby=f'leiden_res{RES}',
              dendrogram=False, 
                standard_scale="var",
             dot_max=0.3,)

In [ ]:
remove_markers(ALL_T)

In [ ]:
try:
    # Define the color mapping
    COLOR = {
        'Dermis': '#D8C59A',
        'Superficial': '#F87A7B'
    }

    # Map the "leiden_res{RES}" column to new subtypes
    #adata_i.obs["t_cellsubtypes"] = adata_i.obs[f"leiden_res{RES}"].map(RENAME)

    # Plot the UMAP with the specified colors
    sc.pl.umap(
        adata_i,  
        color=["t_cellsubtypes"],
        s=200,
        legend_loc="on data",
        legend_fontsize=40,
        legend_fontoutline=2,
        palette=[COLOR[k] for k in adata_i.obs["t_cellsubtypes"].unique()]  # Apply the custom colors
        
        
    )
    import matplotlib.colors as mcolors
    from matplotlib.colors import ListedColormap



    # Convert the color list to a ListedColormap
    color_palette = ListedColormap([COLOR[k] for k in COLOR.keys()])

    # Iterate through unique IDs in adata.obs["info_id"]
    for x in adata.obs["info_id"].unique():
        # Filter the data
        adata_ii = adata_i[adata_i.obs["info_id"] == x]
        adata_iii = adata[adata.obs["info_id"] == x]

        # Plot using Squidpy's spatial_scatter
        sq.pl.spatial_scatter(
            adata_ii,
            library_id="spatial",
            shape=None,
            color='t_cellsubtypes',  # Your desired column
            size=100,
            title='',
            edgecolor="black",
            linewidth=0.1,
            palette=color_palette  # Pass the ListedColormap object
        )
except:
    print(" adata_i.obs[t_cellsubtypes] not present")

In [ ]:
adata_i

In [ ]:
t_dict = {'Conventional': ['CD4', 'CD8A'],
 'Treg': ['FOXP3', 'TIGIT', 'CTLA4'],
'Activated_Treg': ['LRRC32', 'F5', 'NR4A3', 'NR4A1'],
 'TR1': ['LAG3'],
 'Naive/Tcm': ['SELL', 'CCR7', 'S1PR1', 'TCF7'],
 'Th': ['CD40LG', 'MCAM', 'CCR6'],
 'CD8A+ cytotoxic T cells': ['CD8A', 'GZMK', 'CXCR3'],
 'Cytotoxic': ['GZMA'],
 'Tissue-residency\n markers': ['ITGAE', 'ZNF683', 'ENTPD1'],
 'Type 2-associated': ['IL22', 'IL13', 'PDLIM4', 'CCL1', 'CCL17'],
 'T_17': ['IL17F', 'CCL20', 'CTSH', 'CCR6', 'RORC', 'TNFRSF8', 'ADAM12'],
 'Gamma-delta': ['EMP1'],
 'Innate': ['KIT', 'KLRC1'],
 'NK': [],
 'NK+ILC1': ['KLRD1'],
 'ILC1_NK': ['IRF8'],
 'ILC1/3': ['XCL2', 'CSF2'],
 'ILC3': ['TMPRSS11E'],
 'ILC2+3': [],
 'ILC2': ['GATA3', 'PTGDR2', 'IL17RB', 'IL1RL1', 'PPARG', 'PTGS2', 'IL4', 'IL31'],
 'Cycling': ['UBE2C', 'MKI67', 'TOP2A']}
# sc.pl.dotplot(adata_i, 
#               t_dict,
#               groupby='t_cellsubtypes',
#               dendrogram=False, 
#                 #standard_scale="var"
#               vmax=1.5,
#              dot_max=0.3,)

try:
    sc.pl.DotPlot(adata_i, 
                  remove_markers(t_dict),
                  groupby='t_cellsubtypes',
                #  dendrogram=False, 
                    #standard_scale="var"
                  vmax=1.5,
              #   dot_max=0.3,
                 ) \
        .style(cmap='Reds', color_on='square', dot_edge_color='white', dot_edge_lw=1, grid=True).show()
    # sc.pl.DotPlot(
except:
       sc.pl.DotPlot(adata_i, 
                  remove_markers(t_dict),
                  groupby=f'leiden_res{RES}',
                #  dendrogram=False, 
                    #standard_scale="var"
                  vmax=1.5,
              #   dot_max=0.3,
                 ) \
        .style(cmap='Reds', color_on='square', dot_edge_color='white', dot_edge_lw=1, grid=True).show()
    # sc.pl.DotPlot(

In [ ]:
t_dict = {'Conventional': ['CD4', 'CD8A'],
# 'Treg': ['FOXP3', 'TIGIT', 'CTLA4'],
 #'Activated_Treg': ['LRRC32', 'F5', 'NR4A3', 'NR4A1'],
 #'TR1': ['LAG3'],
# 'Naive/Tcm': ['SELL', 'CCR7', 'S1PR1', 'TCF7'],
 #'Th': ['CD40LG', 'MCAM', 'CCR6'],
# 'CD8A+ cytotoxic T cells': ['CD8A', 'GZMK', 'CXCR3'],
 #'Cytotoxic': ['GZMA'],
 'Tissue-residency\n markers': ['ITGAE', 'ZNF683', 'ENTPD1'],
 'Type 2-associated': ['IL22', 'IL13', 'PDLIM4', 'CCL1', 'CCL17'],
 #'T_17': ['IL17F', 'CCL20', 'CTSH', 'CCR6', 'RORC', 'TNFRSF8', 'ADAM12'],
 #'Gamma-delta': ['EMP1'],
 #'Innate': ['KIT', 'KLRC1'],
 #'NK': [],
 #'NK+ILC1': ['KLRD1'],
 #'ILC1_NK': ['IRF8'],
 #'ILC1/3': ['XCL2', 'CSF2'],
 #'ILC3': ['TMPRSS11E'],
 #'ILC2+3': [],
# 'ILC2': ['GATA3', 'PTGDR2', 'IL17RB', 'IL1RL1', 'PPARG', 'PTGS2', 'IL4', 'IL31'],
 'Cycling': ['UBE2C', 'MKI67', 'TOP2A']}
# sc.pl.dotplot(adata_i, 
#               t_dict,
#               groupby='t_cellsubtypes',
#               dendrogram=False, 
#                 #standard_scale="var"
#               vmax=1.5,
#              dot_max=0.3,)

try:
    sc.pl.DotPlot(adata_i, 
                  remove_markers(t_dict),
                  groupby='t_cellsubtypes',
                #  dendrogram=False, 
                    #standard_scale="var"
                  vmax=1.5,
              #   dot_max=0.3,
                 ) \
        .style(cmap='Reds', color_on='square', dot_edge_color='black', dot_edge_lw=1, grid=True).show()
    # sc.pl.DotPlot(
except:
       sc.pl.DotPlot(adata_i, 
                  remove_markers(t_dict),
                  groupby=f'leiden_res{RES}',
                #  dendrogram=False, 
                    #standard_scale="var"
                  vmax=1.5,
              #   dot_max=0.3,
                 ) \
        .style(cmap='Reds', color_on='square', dot_edge_color='black', dot_edge_lw=1, grid=True).show()
    # sc.pl.DotPlot(

In [ ]:
# sc.pl.DotPlot(adata_i, 
#               t_dict,
#               groupby='t_cellsubtypes',
#             #  dendrogram=False, 
#                 #standard_scale="var"
#               vmax=1.5,
#           #   dot_max=0.3,
#              ) \
#     .style(cmap='Reds', color_on='square', dot_edge_color='black', dot_edge_lw=1, grid=True).show()
# # sc.pl.DotPlot(

In [ ]:
# RENAME  = {'0': "Dermis",
#            '1': "Superficial" }

# adata_i.obs["t_cellsubtypes"] =adata_i.obs[ f"leiden_res{RES}"].map(RENAME)
# sc.pl.umap(adata_i,  
#            color=["t_cellsubtypes"],
#            s=200,legend_loc="on data",
#            legend_fontsize=8
#           )

# in this plot, how can i colour:
#        'Dermis': '#8C6A3B',
#     'Superficial': '#F87A7B',

In [ ]:
# RES=0.1
# sc.tl.leiden(adata_i, #restrict_to=(CATEGORY,subset_cluster), 
#              resolution=RES, random_state=1, key_added=f'leiden_res{RES}') #neighbors_key='neighbor_30')


# sc.settings.set_figure_params(dpi=100, facecolor="white", frameon=False, figsize=(12, 12))
# sc.pl.umap(adata_i,  
#            color=[ key_celltype, f"leiden_res{RES}"],
#            s=200,legend_loc="on data",
#            legend_fontsize=8
#           )

# for x in adata.obs["info_id"].unique():
#     adata_ii=adata_i[adata_i.obs["info_id"]==x]
#     adata_iii=adata[adata.obs["info_id"]==x]

#     sq.pl.spatial_scatter(
#             adata_ii,
#             library_id="spatial",
#             shape=None,
#             color=f'leiden_res{RES}',
#             size=100,
#             title=''
#         )

#     # try:
#     #     adata_i.uns.pop('niche_colors')
#     # except:
#     #     1
#     sq.pl.spatial_scatter(
#             adata_iii,
#             library_id="spatial",
#             shape=None,
#             color=f'NICHE_NAMES',
#             size=10,
#             title=''
#         )

# # sc.settings.set_figure_params(dpi=100, facecolor="white", frameon=False, figsize=(12, 12))

In [ ]:
import pandas as pd
# #adata.uns['log1p']['base'] = None
CATEGORY = f"leiden_res{RES}"
#ADATA = adata_i

sc.tl.rank_genes_groups(adata_i, CATEGORY, method='t-test', key_added="de_leiden");
df2 = pd.DataFrame(adata_i.uns['de_leiden']['names'])
for i,x in enumerate(df2.columns):
     print(i,":",x)

In [ ]:
CATEGORY=f"leiden_res{RES}"
select_population = list(df2.columns)[0
                                     ]
print(select_population)
GENE_LIST_DEG_ALL =  df2[select_population][:500]
GENE_LIST_DEG_ALL = [x for x in GENE_LIST_DEG_ALL if x not in MELANOMA_GENES]
genes0 = GENE_LIST_DEG_ALL[:50]
genes1 = GENE_LIST_DEG_ALL[50:100]
genes2 = GENE_LIST_DEG_ALL[100:150]
genes3 = GENE_LIST_DEG_ALL[150:200]
genes4 = GENE_LIST_DEG_ALL[200:250]
genes5 = GENE_LIST_DEG_ALL[250:300]
genes6 = GENE_LIST_DEG_ALL[300:350]
genes7 = GENE_LIST_DEG_ALL[350:400]
genes8 = GENE_LIST_DEG_ALL[400:450]
genes9 = GENE_LIST_DEG_ALL[450:500]

sc.pl.dotplot(
    adata_i,
    genes0,
    groupby=CATEGORY,
    #standard_scale="var",
    dendrogram=False,
) 
sc.pl.dotplot(
    adata_i,
    genes1,
    groupby=CATEGORY,
    #standard_scale="var",
    dendrogram=False,
) 
sc.pl.dotplot(
    adata_i,
    genes2,
    groupby=CATEGORY,
    
    #standard_scale="var",
    dendrogram=False,
) 
# sc.pl.dotplot(
#     adata_subset,
#     genes3,
#     groupby="celltype_annotation4",
#     standard_scale="var",
#     dendrogram=False,
# )

In [ ]:
# MELANOMA_DEGS =

In [ ]:
# sc.pl.dotplot(
#     adata,
#     genes1,
#     groupby=key_celltype,
    
#     #standard_scale="var",
#     dendrogram=False,
# )

In [ ]:
# adata_i

In [ ]:
STOP